"""delete token from ding user

Revision ID: 0443e826c6e9
Revises: 8837d30ca3f1
Create Date: 2026-02-05 22:47:14.709613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0443e826c6e9'
down_revision: Union[str, Sequence[str], None] = '8837d30ca3f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dingding_user', 'refresh_token')
    op.drop_column('dingding_user', 'access_token')
    op.drop_column('dingding_user', 'refresh_token_expire_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dingding_user', sa.Column('refresh_token_expire_at', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('dingding_user', sa.Column('access_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('dingding_user', sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
