"""add candidate search profile tables

Revision ID: 80d68ac7591f
Revises: a1c9d4e5f6a7
Create Date: 2026-07-07 11:55:02.274015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d68ac7591f'
down_revision: Union[str, Sequence[str], None] = 'a1c9d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_index_outbox',
    sa.Column('candidate_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.Enum('upsert', 'delete', name='candidateindexeventtypeenum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'succeeded', 'failed', name='candidateindexeventstatusenum'), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.BigInteger(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_candidate_index_outbox_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_index_outbox')),
    sa.UniqueConstraint('candidate_id', 'event_type', 'profile_version', name='uq_candidate_index_outbox_candidate_event_version')
    )
    op.create_index(op.f('ix_candidate_index_outbox_candidate_id'), 'candidate_index_outbox', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_index_outbox_status'), 'candidate_index_outbox', ['status'], unique=False)
    op.create_table('candidate_search_profiles',
    sa.Column('candidate_id', sa.String(length=100), nullable=False),
    sa.Column('profile_text', sa.Text(), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('indexed_version', sa.Integer(), nullable=True),
    sa.Column('last_index_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_candidate_search_profiles_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_search_profiles'))
    )
    op.create_index(op.f('ix_candidate_search_profiles_candidate_id'), 'candidate_search_profiles', ['candidate_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_search_profiles_candidate_id'), table_name='candidate_search_profiles')
    op.drop_table('candidate_search_profiles')
    op.drop_index(op.f('ix_candidate_index_outbox_status'), table_name='candidate_index_outbox')
    op.drop_index(op.f('ix_candidate_index_outbox_candidate_id'), table_name='candidate_index_outbox')
    op.drop_table('candidate_index_outbox')
    op.execute("DROP TYPE candidateindexeventstatusenum")
    op.execute("DROP TYPE candidateindexeventtypeenum")
    # ### end Alembic commands ###
