"""init model

Revision ID: 8837d30ca3f1
Revises: 
Create Date: 2026-02-03 14:02:43.397551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8837d30ca3f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('_password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('realname', sa.String(length=50), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('department_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'BLOCKED', 'RESIGNED', name='userstatus'), nullable=False),
    sa.Column('is_hr', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_users_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('dingding_user',
    sa.Column('nick', sa.String(length=100), nullable=False),
    sa.Column('union_id', sa.String(length=100), nullable=False),
    sa.Column('open_id', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token_expire_at', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dingding_user_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dingding_user'))
    )
    op.create_index(op.f('ix_dingding_user_mobile'), 'dingding_user', ['mobile'], unique=True)
    op.create_index(op.f('ix_dingding_user_open_id'), 'dingding_user', ['open_id'], unique=True)
    op.create_index(op.f('ix_dingding_user_union_id'), 'dingding_user', ['union_id'], unique=True)
    op.create_table('hr_managed_departments',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_hr_managed_departments_department_id_departments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_hr_managed_departments_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'department_id', name=op.f('pk_hr_managed_departments'))
    )
    op.create_table('positions',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('min_salary', sa.Integer(), nullable=True),
    sa.Column('max_salary', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('recruitment_count', sa.Integer(), nullable=False),
    sa.Column('education', sa.Enum('COLLEGE', 'BACHELOR', 'MASTER', 'DOCTOR', 'UNKNOWN', name='educationenum'), nullable=False),
    sa.Column('work_year', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('department_id', sa.String(length=100), nullable=False),
    sa.Column('creator_id', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_positions_creator_id_users')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_positions_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions'))
    )
    op.create_table('resumes',
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('uploader_id', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name=op.f('fk_resumes_uploader_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resumes'))
    )
    op.create_table('candidates',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'UNKNOWN', name='genderenum'), nullable=False),
    sa.Column('birthday', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('work_experience', sa.Text(), nullable=True),
    sa.Column('project_experience', sa.Text(), nullable=True),
    sa.Column('education_experience', sa.Text(), nullable=True),
    sa.Column('self_evaluation', sa.Text(), nullable=True),
    sa.Column('other_information', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('已投递', 'AI筛选失败', 'AI筛选成功', '待面试', '拒绝面试', '面试通过', '面试未通过', '已入职', '已拒绝', name='candidatestatusenum'), nullable=False),
    sa.Column('position_id', sa.String(length=100), nullable=False),
    sa.Column('resume_id', sa.String(length=100), nullable=False),
    sa.Column('creator_id', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_candidates_creator_id_users')),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_candidates_position_id_positions')),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_candidates_resume_id_resumes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates'))
    )
    op.create_index(op.f('ix_candidates_phone_number'), 'candidates', ['phone_number'], unique=False)
    op.create_table('candidate_ai_scores',
    sa.Column('work_experience_score', sa.Integer(), nullable=False),
    sa.Column('technical_skills_score', sa.Integer(), nullable=False),
    sa.Column('soft_skills_score', sa.Integer(), nullable=False),
    sa.Column('educational_background_score', sa.Integer(), nullable=False),
    sa.Column('project_experience_score', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('candidate_id', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_candidate_ai_scores_candidate_id_candidates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_ai_scores'))
    )
    op.create_table('interviews',
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('result', sa.Enum('PASSED', 'FAILED', name='interviewresultenum'), nullable=True),
    sa.Column('candidate_id', sa.String(length=100), nullable=False),
    sa.Column('interviewer_id', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_interviews_candidate_id_candidates')),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], name=op.f('fk_interviews_interviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interviews')),
    sa.UniqueConstraint('candidate_id', name=op.f('uq_interviews_candidate_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interviews')
    op.drop_table('candidate_ai_scores')
    op.drop_index(op.f('ix_candidates_phone_number'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_table('resumes')
    op.drop_table('positions')
    op.drop_table('hr_managed_departments')
    op.drop_index(op.f('ix_dingding_user_union_id'), table_name='dingding_user')
    op.drop_index(op.f('ix_dingding_user_open_id'), table_name='dingding_user')
    op.drop_index(op.f('ix_dingding_user_mobile'), table_name='dingding_user')
    op.drop_table('dingding_user')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
