"""Java 后端 / 云原生合成简历。"""

RESUMES = [
    {
        "synthetic_key": "java_cloud_01",
        "category": "Java云原生",
        "tags": ["Java", "Spring Cloud", "Kubernetes", "微服务"],
        "status": "待面试",
        "department": "技术部",
        "name": "刘承泽",
        "headline": "Java 云原生工程师｜Spring Cloud / Kubernetes｜8年经验",
        "target_position": "资深 Java 后端工程师",
        "years": 8,
        "city": "成都 / 上海",
        "phone": "138-3003-0001",
        "email": "liu.chengze@example.com",
        "availability": "1个月",
        "relevant_for": ["Java微服务", "Kubernetes"],
        "distractor_for": ["Python FastAPI Milvus", "RAG"],
        "eval_notes": "跨技术栈干扰：微服务/K8s 词易与工程化检索混淆。",
        "highlights": [
            "长期负责高并发业务与微服务治理，熟悉 Spring Boot/Cloud、Kafka、Kubernetes。",
            "具备订单、审批流建模经验，重视可观测性与容量规划。",
            "无 Python RAG / Milvus 经验。",
        ],
        "experiences": [
            {
                "company": "川岳科技",
                "title": "资深 Java 后端",
                "period": "2020.05 - 至今",
                "summary": "企业协同平台。",
                "bullets": [
                    "单体拆微服务：账户、审批、消息、文件与审计。",
                    "Kubernetes + GitLab CI 灰度发布，回滚时间缩短。",
                ],
            },
            {
                "company": "万象电商",
                "title": "Java 开发",
                "period": "2016.07 - 2020.04",
                "summary": "订单库存。",
                "bullets": ["Kafka 解耦下单与库存。"],
            },
        ],
        "projects": [
            {
                "name": "云原生招聘平台基础服务改造",
                "period": "2023.03 - 2024.03",
                "summary": "SaaS 稳定性。",
                "bullets": ["统一鉴权、链路追踪与限流。"],
            }
        ],
        "education": {
            "school": "电子科技大学",
            "major": "软件工程",
            "degree": "本科",
            "period": "2012.09 - 2016.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Java", "Spring Cloud", "Kubernetes", "Kafka", "MySQL", "Redis", "可观测性"],
        "other": ["期望薪资：36K-45K"],
    },
    {
        "synthetic_key": "java_payment_01",
        "category": "Java支付订单",
        "tags": ["Java", "支付", "订单", "Kafka"],
        "status": "已投递",
        "department": "技术部",
        "name": "马思远",
        "headline": "Java 交易后端｜支付 / 订单｜7年经验",
        "target_position": "Java 支付工程师",
        "years": 7,
        "city": "杭州",
        "phone": "138-3003-0002",
        "email": "ma.siyuan@example.com",
        "availability": "2周内",
        "relevant_for": ["支付订单", "Kafka"],
        "distractor_for": ["风控实时特征平台"],
        "eval_notes": "干扰：支付/订单后端，非风控特征平台。",
        "highlights": [
            "订单状态机、支付回调幂等与库存扣减。",
            "Spring Boot + Kafka + MySQL。",
            "调用过风控接口，但不建设特征服务。",
        ],
        "experiences": [
            {
                "company": "浙易支付",
                "title": "高级 Java",
                "period": "2019.09 - 至今",
                "summary": "交易核心。",
                "bullets": [
                    "支付回调与退款编排。",
                    "高峰期容量评估与限流。",
                ],
            },
            {
                "company": "橙果零售",
                "title": "Java 开发",
                "period": "2017.07 - 2019.08",
                "summary": "订单中心。",
                "bullets": ["订单拆单合单。"],
            },
        ],
        "projects": [
            {
                "name": "统一收银台",
                "period": "2023.02 - 2024.02",
                "summary": "多渠道支付。",
                "bullets": ["渠道路由与对账。"],
            }
        ],
        "education": {
            "school": "浙江大学",
            "major": "计算机",
            "degree": "本科",
            "period": "2013.09 - 2017.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Java", "Spring Boot", "Kafka", "MySQL", "支付", "订单状态机"],
        "other": ["期望薪资：34K-42K"],
    },
    {
        "synthetic_key": "java_auth_01",
        "category": "Java权限中台",
        "tags": ["Java", "权限", "Spring Security", "OAuth"],
        "status": "AI筛选通过",
        "department": "算法/AI平台",
        "name": "高翎溪",
        "headline": "Java 权限中台工程师｜IAM / OAuth｜5年经验",
        "target_position": "Java 后端工程师",
        "years": 5,
        "city": "北京",
        "phone": "138-3003-0003",
        "email": "gao.lingxi@example.com",
        "availability": "1个月",
        "relevant_for": ["权限系统", "IAM"],
        "distractor_for": ["Python FastAPI Milvus"],
        "eval_notes": "跨栈干扰：权限词在 RAG 场景常见，但是人是 Java IAM。",
        "highlights": [
            "熟悉 Spring Security、OAuth2、RBAC 与资源范围。",
            "建设统一登录与审计。",
            "无向量检索经验。",
        ],
        "experiences": [
            {
                "company": "安御科技",
                "title": "Java 后端",
                "period": "2021.03 - 至今",
                "summary": "IAM 平台。",
                "bullets": ["统一认证、角色模板与审计日志。"],
            },
            {
                "company": "北银软件",
                "title": "Java 开发",
                "period": "2019.07 - 2021.02",
                "summary": "内部账号体系。",
                "bullets": ["单点登录改造。"],
            },
        ],
        "projects": [
            {
                "name": "企业统一权限中心",
                "period": "2023.05 - 2024.08",
                "summary": "多应用鉴权。",
                "bullets": ["部门范围策略与 token 撤销。"],
            }
        ],
        "education": {
            "school": "北京交通大学",
            "major": "信息安全",
            "degree": "本科",
            "period": "2015.09 - 2019.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Java", "Spring Security", "OAuth2", "RBAC", "MySQL", "Redis"],
        "other": ["期望薪资：30K-38K"],
    },
    {
        "synthetic_key": "java_kafka_01",
        "category": "Java消息驱动",
        "tags": ["Java", "Kafka", "微服务", "异步"],
        "status": "AI筛选未通过",
        "department": "技术部",
        "name": "宋啟恒",
        "headline": "Java 后端工程师｜Kafka / 事件驱动｜6年经验",
        "target_position": "Java 后端工程师",
        "years": 6,
        "city": "深圳",
        "phone": "138-3003-0004",
        "email": "song.qiheng@example.com",
        "availability": "2周内",
        "relevant_for": ["Kafka", "事件驱动"],
        "distractor_for": ["风控实时特征平台"],
        "eval_notes": "干扰：会 Kafka，但做消息驱动业务而非实时特征。",
        "highlights": [
            "事件驱动拆分通知、积分与物流跟踪。",
            "熟悉消费者组、重试与死信。",
            "无 Flink 特征计算经验。",
        ],
        "experiences": [
            {
                "company": "深航科技",
                "title": "高级 Java",
                "period": "2020.01 - 至今",
                "summary": "电商中台。",
                "bullets": ["Kafka 解耦下单后置链路。"],
            },
            {
                "company": "鹏城软件",
                "title": "Java 开发",
                "period": "2018.07 - 2019.12",
                "summary": "物流跟踪。",
                "bullets": ["消息积压治理。"],
            },
        ],
        "projects": [
            {
                "name": "统一事件总线",
                "period": "2023.01 - 2023.11",
                "summary": "事件 Schema 治理。",
                "bullets": ["契约测试与回溯重放。"],
            }
        ],
        "education": {
            "school": "深圳大学",
            "major": "软件工程",
            "degree": "本科",
            "period": "2014.09 - 2018.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Java", "Spring Boot", "Kafka", "微服务", "死信队列"],
        "other": ["期望薪资：32K-40K"],
    },
    {
        "synthetic_key": "java_k8s_01",
        "category": "Java平台工程",
        "tags": ["Java", "Kubernetes", "CI/CD", "平台"],
        "status": "已入职",
        "department": "技术部",
        "name": "汪澄空",
        "headline": "Java 平台工程师｜K8s / 发布治理｜7年经验",
        "target_position": "平台工程师",
        "years": 7,
        "city": "上海",
        "phone": "138-3003-0005",
        "email": "wang.chengkong@example.com",
        "availability": "在职",
        "relevant_for": ["Kubernetes", "平台工程"],
        "distractor_for": ["DevOps", "MLOps"],
        "eval_notes": "干扰：K8s/CI 词与 DevOps/MLOps 相近。",
        "highlights": [
            "关注 Java 服务上云、发布模板与资源配额。",
            "熟悉 Helm、GitOps 与灰度。",
            "不做模型部署与训推流水线。",
        ],
        "experiences": [
            {
                "company": "云栈平台",
                "title": "平台工程师",
                "period": "2019.06 - 至今",
                "summary": "应用托管。",
                "bullets": ["标准化 Deployment / HPA 模板。"],
            },
            {
                "company": "申城研发",
                "title": "Java 开发",
                "period": "2017.07 - 2019.05",
                "summary": "业务后端。",
                "bullets": ["Spring Boot 业务服务。"],
            },
        ],
        "projects": [
            {
                "name": "统一发布平台",
                "period": "2023.02 - 2024.05",
                "summary": "自助发布。",
                "bullets": ["审批流 + 金丝雀。"],
            }
        ],
        "education": {
            "school": "上海大学",
            "major": "计算机",
            "degree": "本科",
            "period": "2013.09 - 2017.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Java", "Kubernetes", "Helm", "GitOps", "CI/CD", "可观测性"],
        "other": ["期望薪资：38K-48K"],
    },
    {
        "synthetic_key": "java_micro_01",
        "category": "Java微服务",
        "tags": ["Java", "Spring Cloud", "网关", "配置中心"],
        "status": "已投递",
        "department": "技术部",
        "name": "邓泊然",
        "headline": "Java 微服务工程师｜Spring Cloud｜5年经验",
        "target_position": "Java 微服务工程师",
        "years": 5,
        "city": "广州",
        "phone": "138-3003-0006",
        "email": "deng.boran@example.com",
        "availability": "随时",
        "relevant_for": ["Spring Cloud", "微服务"],
        "distractor_for": ["Python FastAPI Milvus"],
        "eval_notes": "技术词误召回检验。",
        "highlights": [
            "网关、注册发现、配置中心与熔断。",
            "熟悉开放接口治理。",
            "无 AI/向量相关经验。",
        ],
        "experiences": [
            {
                "company": "粤海软件",
                "title": "Java 后端",
                "period": "2021.01 - 至今",
                "summary": "微服务基建。",
                "bullets": ["Gateway 鉴权与限流。"],
            },
            {
                "company": "南岭互联",
                "title": "Java 开发",
                "period": "2019.07 - 2020.12",
                "summary": "业务服务。",
                "bullets": ["服务拆分落地。"],
            },
        ],
        "projects": [
            {
                "name": "统一 API 网关",
                "period": "2023.04 - 2024.01",
                "summary": "开放平台。",
                "bullets": ["签名校验与租户限流。"],
            }
        ],
        "education": {
            "school": "华南师范大学",
            "major": "软件工程",
            "degree": "本科",
            "period": "2015.09 - 2019.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Java", "Spring Cloud", "Gateway", "Nacos", "Sentinel"],
        "other": ["期望薪资：28K-35K"],
    },
    {
        "synthetic_key": "java_order_risk_01",
        "category": "Java风控对接后端",
        "tags": ["Java", "风控对接", "订单", "反欺诈调用"],
        "status": "待面试",
        "department": "技术部",
        "name": "姚庭岳",
        "headline": "Java 后端工程师｜订单 / 风控对接｜6年经验",
        "target_position": "Java 后端工程师",
        "years": 6,
        "city": "北京",
        "phone": "138-3003-0007",
        "email": "yao.tingyue@example.com",
        "availability": "1个月",
        "relevant_for": ["有风控平台经验的后端工程师"],
        "distractor_for": ["风控实时特征平台"],
        "eval_notes": "中度相关/干扰：会对接风控，但不建特征与实时决策平台。",
        "highlights": [
            "订单链路中对接第三方反欺诈与额度决策接口。",
            "关注超时、降级与结果落库。",
            "不负责特征工程、评分卡训练与 Flink 实时计算。",
        ],
        "experiences": [
            {
                "company": "信易金科",
                "title": "高级 Java",
                "period": "2020.04 - 至今",
                "summary": "信贷进件后端。",
                "bullets": [
                    "封装风控网关 SDK，统一超时与熔断。",
                    "根据决策码驱动订单通过/拒绝。",
                ],
            },
            {
                "company": "京橙科技",
                "title": "Java 开发",
                "period": "2018.07 - 2020.03",
                "summary": "电商订单。",
                "bullets": ["订单查询与售后。"],
            },
        ],
        "projects": [
            {
                "name": "进件风控编排",
                "period": "2023.06 - 2024.06",
                "summary": "编排外部决策。",
                "bullets": ["异步回调与人工复核队列。"],
            }
        ],
        "education": {
            "school": "中央财经大学",
            "major": "计算机",
            "degree": "本科",
            "period": "2014.09 - 2018.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Java", "Spring Boot", "风控对接", "订单", "熔断降级", "MySQL"],
        "other": ["期望薪资：33K-40K"],
    },
]
