"""数据工程、前端、DevOps、HR、产品合成简历。"""

RESUMES = [
    # ---- 数据工程 / 数据分析 × 5 ----
    {
        "synthetic_key": "de_warehouse_01",
        "category": "数据工程-数仓",
        "tags": ["数仓", "ETL", "Hive", "维度建模"],
        "status": "已投递",
        "department": "数据/风控",
        "name": "邹明川",
        "headline": "数据仓库工程师｜Hive / 维度建模｜5年经验",
        "target_position": "数据仓库工程师",
        "years": 5,
        "city": "成都",
        "phone": "138-5005-0001",
        "email": "zou.mingchuan@example.com",
        "availability": "1个月",
        "relevant_for": ["数据工程", "数仓"],
        "distractor_for": ["风控实时特征平台", "NLP算法"],
        "eval_notes": "区分数据工程与算法/实时风控。",
        "highlights": [
            "主题域建模、缓慢变化维与数据质量校验。",
            "熟悉 Hive/Spark SQL。",
            "无在线特征与模型训练经验。",
        ],
        "experiences": [
            {
                "company": "蜀数仓",
                "title": "数仓工程师",
                "period": "2021.03 - 至今",
                "summary": "业务主题仓。",
                "bullets": ["建设招聘与人力主题层。"],
            },
            {
                "company": "天府数据",
                "title": "ETL 开发",
                "period": "2019.07 - 2021.02",
                "summary": "数据集成。",
                "bullets": ["批次同步与对账。"],
            },
        ],
        "projects": [
            {
                "name": "ODS-DWD-DWS 分层改造",
                "period": "2023.01 - 2024.03",
                "summary": "分层规范。",
                "bullets": ["统一口径与血缘。"],
            }
        ],
        "education": {
            "school": "西南交通大学",
            "major": "计算机",
            "degree": "本科",
            "period": "2015.09 - 2019.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Hive", "Spark SQL", "ETL", "维度建模", "数据质量"],
        "other": ["期望薪资：25K-32K"],
    },
    {
        "synthetic_key": "de_flink_01",
        "category": "数据工程-实时",
        "tags": ["Flink", "Spark", "实时数仓", "Kafka"],
        "status": "待面试",
        "department": "数据/风控",
        "name": "陶若涵",
        "headline": "实时数据工程师｜Flink / Kafka｜4年经验",
        "target_position": "实时数据工程师",
        "years": 4,
        "city": "杭州",
        "phone": "138-5005-0002",
        "email": "tao.ruohan@example.com",
        "availability": "2周内",
        "relevant_for": ["Flink", "实时数仓"],
        "distractor_for": ["风控实时特征平台"],
        "eval_notes": "干扰：会 Flink，但做实时数仓指标，非风控特征。",
        "highlights": [
            "实时大盘指标、UV/PV、漏斗事件流。",
            "Flink SQL + Kafka。",
            "不服务风控决策特征点查。",
        ],
        "experiences": [
            {
                "company": "杭流数据",
                "title": "实时数据开发",
                "period": "2022.05 - 至今",
                "summary": "运营实时看板。",
                "bullets": ["Flink 计算活跃与转化。"],
            },
            {
                "company": "云溪",
                "title": "数据开发",
                "period": "2021.07 - 2022.04",
                "summary": "批处理。",
                "bullets": ["Spark 任务。"],
            },
        ],
        "projects": [
            {
                "name": "招聘漏斗实时大盘",
                "period": "2023.09 - 2024.08",
                "summary": "事件流。",
                "bullets": ["投递到 offer 漏斗实时统计。"],
            }
        ],
        "education": {
            "school": "杭州师范大学",
            "major": "数据科学",
            "degree": "本科",
            "period": "2017.09 - 2021.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Flink", "Kafka", "Spark", "实时数仓", "ClickHouse"],
        "other": ["期望薪资：28K-35K"],
    },
    {
        "synthetic_key": "da_bi_01",
        "category": "数据分析-BI",
        "tags": ["BI", "数据分析", "SQL", "看板"],
        "status": "AI筛选未通过",
        "department": "运营部",
        "name": "贺昕妍",
        "headline": "数据分析师｜BI / 经营分析｜4年经验",
        "target_position": "数据分析师",
        "years": 4,
        "city": "上海",
        "phone": "138-5005-0003",
        "email": "he.xinyan@example.com",
        "availability": "随时",
        "relevant_for": ["数据分析", "BI"],
        "distractor_for": ["风控实时特征平台", "数据工程"],
        "eval_notes": "干扰：普通数据分析。",
        "highlights": [
            "业务看板、漏斗与归因分析。",
            "熟悉 SQL、Tableau/Metabase。",
            "不写 Spark/Flink 生产任务。",
        ],
        "experiences": [
            {
                "company": "蓝海电商",
                "title": "数据分析师",
                "period": "2022.02 - 至今",
                "summary": "经营分析。",
                "bullets": ["GMV、转化与渠道 ROI。"],
            },
            {
                "company": "洞察咨询",
                "title": "分析助理",
                "period": "2021.07 - 2022.01",
                "summary": "项目分析。",
                "bullets": ["问卷与报告。"],
            },
        ],
        "projects": [
            {
                "name": "经营驾驶舱",
                "period": "2023.03 - 2024.02",
                "summary": "BI 看板。",
                "bullets": ["周报自动化。"],
            }
        ],
        "education": {
            "school": "东华大学",
            "major": "统计学",
            "degree": "本科",
            "period": "2017.09 - 2021.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["SQL", "BI", "Tableau", "Excel", "经营分析"],
        "other": ["期望薪资：18K-25K"],
    },
    {
        "synthetic_key": "da_recruit_01",
        "category": "招聘数据分析",
        "tags": ["招聘数据分析", "漏斗", "SQL", "人才运营"],
        "status": "AI筛选通过",
        "department": "运营部",
        "name": "纪清禾",
        "headline": "招聘数据分析｜漏斗 / 渠道｜3年经验",
        "target_position": "招聘数据分析师",
        "years": 3,
        "city": "北京",
        "phone": "138-5005-0004",
        "email": "ji.qinghe@example.com",
        "availability": "2周内",
        "relevant_for": ["招聘数据分析"],
        "distractor_for": ["RAG", "数据工程"],
        "eval_notes": "招聘业务分析，非技术候选人。",
        "highlights": [
            "招聘漏斗、渠道效果与面试通过率分析。",
            "协助 HR 做周报。",
            "了解 ATS 字段，不会开发检索系统。",
        ],
        "experiences": [
            {
                "company": "才云 HR",
                "title": "招聘数据分析",
                "period": "2023.01 - 至今",
                "summary": "招聘运营支持。",
                "bullets": ["渠道 CPL 与 offer 接受率。"],
            },
            {
                "company": "实习生项目",
                "title": "数据分析实习",
                "period": "2022.03 - 2022.12",
                "summary": "校园招聘。",
                "bullets": ["校招进度看板。"],
            },
        ],
        "projects": [
            {
                "name": "招聘漏斗可视化",
                "period": "2023.06 - 2024.01",
                "summary": "运营看板。",
                "bullets": ["按部门/岗位拆解转化。"],
            }
        ],
        "education": {
            "school": "中国传媒大学",
            "major": "市场营销",
            "degree": "本科",
            "period": "2018.09 - 2022.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["招聘数据分析", "SQL", "Excel", "漏斗分析", "ATS"],
        "other": ["期望薪资：15K-22K"],
    },
    {
        "synthetic_key": "de_etl_01",
        "category": "数据工程-ETL",
        "tags": ["ETL", "DataX", "同步", "Python"],
        "status": "AI筛选通过",
        "department": "数据/风控",
        "name": "冉博文",
        "headline": "ETL 工程师｜数据同步｜4年经验",
        "target_position": "ETL 工程师",
        "years": 4,
        "city": "西安",
        "phone": "138-5005-0005",
        "email": "ran.bowen@example.com",
        "availability": "1个月",
        "relevant_for": ["ETL", "数据工程"],
        "distractor_for": ["风控实时特征平台"],
        "eval_notes": "普通 ETL，非特征平台。",
        "highlights": [
            "异构库同步、任务监控与补数。",
            "DataX / Python 脚本。",
            "无算法与风控建模。",
        ],
        "experiences": [
            {
                "company": "西咸数据",
                "title": "ETL 工程师",
                "period": "2022.01 - 至今",
                "summary": "同步任务。",
                "bullets": ["业务库到数仓日切。"],
            },
            {
                "company": "秦云",
                "title": "初级开发",
                "period": "2021.07 - 2021.12",
                "summary": "脚本开发。",
                "bullets": ["Python 清洗。"],
            },
        ],
        "projects": [
            {
                "name": "全量/增量同步框架",
                "period": "2023.05 - 2024.04",
                "summary": "同步平台。",
                "bullets": ["失败重跑与告警。"],
            }
        ],
        "education": {
            "school": "西安电子科技大学",
            "major": "软件工程",
            "degree": "本科",
            "period": "2017.09 - 2021.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["ETL", "DataX", "Python", "MySQL", "Hive", "调度"],
        "other": ["期望薪资：20K-28K"],
    },
    # ---- 前端 × 4 ----
    {
        "synthetic_key": "fe_vue_01",
        "category": "前端-Vue",
        "tags": ["Vue", "中后台", "TypeScript"],
        "status": "已投递",
        "department": "技术部",
        "name": "宁嘉树",
        "headline": "前端工程师｜Vue3 / 中后台｜4年经验",
        "target_position": "前端工程师",
        "years": 4,
        "city": "杭州",
        "phone": "138-6006-0001",
        "email": "ning.jiashu@example.com",
        "availability": "2周内",
        "relevant_for": ["Vue前端"],
        "distractor_for": ["Python FastAPI Milvus", "RAG"],
        "eval_notes": "明确负例。",
        "highlights": [
            "Vue3 + TypeScript 中后台。",
            "组件库与权限路由。",
            "不涉及后端检索与向量库。",
        ],
        "experiences": [
            {
                "company": "杭易前端",
                "title": "前端工程师",
                "period": "2022.03 - 至今",
                "summary": "SaaS 管理端。",
                "bullets": ["表格、表单与权限菜单。"],
            },
            {
                "company": "青枝互联",
                "title": "前端",
                "period": "2021.07 - 2022.02",
                "summary": "运营后台。",
                "bullets": ["Vue2 维护。"],
            },
        ],
        "projects": [
            {
                "name": "统一中后台脚手架",
                "period": "2023.04 - 2024.01",
                "summary": "工程化。",
                "bullets": ["微前端与主题。"],
            }
        ],
        "education": {
            "school": "浙江理工大学",
            "major": "软件工程",
            "degree": "本科",
            "period": "2017.09 - 2021.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Vue3", "TypeScript", "Vite", "Element Plus", "Pinia"],
        "other": ["期望薪资：22K-30K"],
    },
    {
        "synthetic_key": "fe_react_01",
        "category": "前端-React",
        "tags": ["React", "中后台", "Hooks"],
        "status": "AI筛选未通过",
        "department": "技术部",
        "name": "孔令择",
        "headline": "前端工程师｜React / Ant Design｜5年经验",
        "target_position": "React 前端工程师",
        "years": 5,
        "city": "北京",
        "phone": "138-6006-0002",
        "email": "kong.lingze@example.com",
        "availability": "1个月",
        "relevant_for": ["React前端"],
        "distractor_for": ["Python FastAPI Milvus"],
        "eval_notes": "明确负例。",
        "highlights": [
            "React Hooks、状态管理与复杂表单。",
            "对接 REST API。",
            "无算法/RAG 经验。",
        ],
        "experiences": [
            {
                "company": "北桥科技",
                "title": "高级前端",
                "period": "2020.08 - 至今",
                "summary": "企业中后台。",
                "bullets": ["ProTable 与流程设计器。"],
            },
            {
                "company": "码农工坊",
                "title": "前端",
                "period": "2019.07 - 2020.07",
                "summary": "ToC 活动页。",
                "bullets": ["H5 适配。"],
            },
        ],
        "projects": [
            {
                "name": "审批流可视化编辑器",
                "period": "2023.01 - 2023.12",
                "summary": "画布编辑。",
                "bullets": ["节点拖拽与校验。"],
            }
        ],
        "education": {
            "school": "北京工业大学",
            "major": "软件工程",
            "degree": "本科",
            "period": "2015.09 - 2019.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["React", "TypeScript", "Ant Design", "Redux", "Webpack"],
        "other": ["期望薪资：28K-36K"],
    },
    {
        "synthetic_key": "fe_viz_01",
        "category": "前端-可视化",
        "tags": ["可视化", "ECharts", "D3", "看板"],
        "status": "待面试",
        "department": "技术部",
        "name": "尹楚歌",
        "headline": "可视化前端｜ECharts / 大屏｜4年经验",
        "target_position": "可视化前端工程师",
        "years": 4,
        "city": "深圳",
        "phone": "138-6006-0003",
        "email": "yin.chuge@example.com",
        "availability": "2周内",
        "relevant_for": ["可视化前端"],
        "distractor_for": ["数据分析", "BI"],
        "eval_notes": "前端可视化负例，易与 BI 混淆。",
        "highlights": [
            "大屏可视化、地图与动态图表。",
            "ECharts / D3。",
            "数据由后端提供，本人不做 ETL。",
        ],
        "experiences": [
            {
                "company": "视界交互",
                "title": "可视化前端",
                "period": "2022.01 - 至今",
                "summary": "指挥舱大屏。",
                "bullets": ["多屏适配与性能优化。"],
            },
            {
                "company": "深图",
                "title": "前端",
                "period": "2021.07 - 2021.12",
                "summary": "报表页。",
                "bullets": ["图表封装。"],
            },
        ],
        "projects": [
            {
                "name": "城市运营数据大屏",
                "period": "2023.06 - 2024.05",
                "summary": "可视化交付。",
                "bullets": ["实时刷新与告警闪烁。"],
            }
        ],
        "education": {
            "school": "深圳技术大学",
            "major": "数字媒体",
            "degree": "本科",
            "period": "2017.09 - 2021.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["ECharts", "D3", "Vue", "Three.js", "大屏可视化"],
        "other": ["期望薪资：24K-32K"],
    },
    {
        "synthetic_key": "fe_ats_01",
        "category": "前端-招聘系统",
        "tags": ["Vue", "ATS前端", "招聘系统"],
        "status": "已入职",
        "department": "技术部",
        "name": "穆清扬",
        "headline": "招聘系统前端｜ATS / Vue｜5年经验",
        "target_position": "前端工程师",
        "years": 5,
        "city": "上海",
        "phone": "138-6006-0004",
        "email": "mu.qingyang@example.com",
        "availability": "在职",
        "relevant_for": ["招聘系统前端"],
        "distractor_for": ["RAG", "技术招聘"],
        "eval_notes": "负例：做 ATS 前端，文案可能出现候选人/简历词。",
        "highlights": [
            "候选人列表、简历预览、面试排期 UI。",
            "Vue + 组件化表单。",
            "了解人才搜索产品需求，但不实现检索算法。",
        ],
        "experiences": [
            {
                "company": "智聘云",
                "title": "前端工程师",
                "period": "2020.09 - 至今",
                "summary": "ATS 前台。",
                "bullets": [
                    "简历上传进度与解析状态展示。",
                    "配合产品做人才搜索结果页，高亮匹配理由（展示层）。",
                ],
            },
            {
                "company": "云图软件",
                "title": "前端",
                "period": "2019.07 - 2020.08",
                "summary": "HR SaaS。",
                "bullets": ["组织架构树组件。"],
            },
        ],
        "projects": [
            {
                "name": "人才搜索结果页改版",
                "period": "2024.02 - 2024.10",
                "summary": "前端交互。",
                "bullets": ["筛选器、匹配理由折叠面板。"],
            }
        ],
        "education": {
            "school": "华东理工大学",
            "major": "软件工程",
            "degree": "本科",
            "period": "2015.09 - 2019.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Vue", "TypeScript", "ATS前端", "简历预览", "中后台"],
        "other": ["期望薪资：30K-38K"],
    },
    # ---- DevOps / MLOps × 4 ----
    {
        "synthetic_key": "devops_k8s_01",
        "category": "DevOps",
        "tags": ["Kubernetes", "CI/CD", "Docker", "可观测性"],
        "status": "已投递",
        "department": "技术部",
        "name": "齐澜舟",
        "headline": "DevOps 工程师｜K8s / CI/CD｜6年经验",
        "target_position": "DevOps 工程师",
        "years": 6,
        "city": "北京",
        "phone": "138-7007-0001",
        "email": "qi.lanzhou@example.com",
        "availability": "1个月",
        "relevant_for": ["DevOps", "Kubernetes"],
        "distractor_for": ["MLOps", "RAG"],
        "eval_notes": "工程化相似词干扰。",
        "highlights": [
            "集群运维、流水线与监控告警。",
            "Docker / Kubernetes / Prometheus。",
            "不负责模型训练与向量检索。",
        ],
        "experiences": [
            {
                "company": "云枢运维",
                "title": "DevOps",
                "period": "2020.02 - 至今",
                "summary": "基础设施工具链。",
                "bullets": ["GitLab CI 模板与集群升级。"],
            },
            {
                "company": "北云",
                "title": "运维工程师",
                "period": "2018.07 - 2020.01",
                "summary": "主机运维。",
                "bullets": ["自动化脚本。"],
            },
        ],
        "projects": [
            {
                "name": "统一可观测性平台",
                "period": "2023.03 - 2024.06",
                "summary": "监控链路。",
                "bullets": ["指标/日志/追踪三合一。"],
            }
        ],
        "education": {
            "school": "北京科技大学",
            "major": "网络工程",
            "degree": "本科",
            "period": "2014.09 - 2018.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Docker", "Kubernetes", "CI/CD", "Prometheus", "Terraform"],
        "other": ["期望薪资：32K-40K"],
    },
    {
        "synthetic_key": "mlops_01",
        "category": "MLOps",
        "tags": ["MLOps", "模型部署", "KServe", "CI/CD"],
        "status": "AI筛选通过",
        "department": "算法/AI平台",
        "name": "常予衡",
        "headline": "MLOps 工程师｜模型部署 / 流水线｜5年经验",
        "target_position": "MLOps 工程师",
        "years": 5,
        "city": "上海",
        "phone": "138-7007-0002",
        "email": "chang.yuheng@example.com",
        "availability": "2周内",
        "relevant_for": ["MLOps", "模型部署"],
        "distractor_for": ["RAG", "Python FastAPI Milvus"],
        "eval_notes": "干扰：模型部署/工程化，易与 RAG 工程混淆。",
        "highlights": [
            "模型注册、镜像构建、灰度发布与回滚。",
            "KServe / Triton / Argo。",
            "熟悉 Embedding 服务部署，但不建设 Milvus 检索应用。",
        ],
        "experiences": [
            {
                "company": "模型工厂",
                "title": "MLOps 工程师",
                "period": "2021.04 - 至今",
                "summary": "训推平台。",
                "bullets": [
                    "模型制品晋级流水线。",
                    "在线推理服务扩缩容。",
                ],
            },
            {
                "company": "数智运维",
                "title": "DevOps",
                "period": "2019.07 - 2021.03",
                "summary": "基础 CI。",
                "bullets": ["容器化落地。"],
            },
        ],
        "projects": [
            {
                "name": "统一模型服务平台",
                "period": "2023.01 - 2024.09",
                "summary": "部署治理。",
                "bullets": ["金丝雀与自动回滚。"],
            }
        ],
        "education": {
            "school": "同济大学",
            "major": "自动化",
            "degree": "本科",
            "period": "2015.09 - 2019.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["MLOps", "KServe", "Docker", "Kubernetes", "模型部署", "Argo"],
        "other": ["期望薪资：35K-45K"],
    },
    {
        "synthetic_key": "devops_cicd_01",
        "category": "DevOps-CI",
        "tags": ["CI/CD", "Jenkins", "GitLab", "自动化"],
        "status": "AI筛选未通过",
        "department": "运营部",
        "name": "裴景行",
        "headline": "CI/CD 工程师｜流水线｜4年经验",
        "target_position": "CI/CD 工程师",
        "years": 4,
        "city": "南京",
        "phone": "138-7007-0003",
        "email": "pei.jingxing@example.com",
        "availability": "随时",
        "relevant_for": ["CI/CD"],
        "distractor_for": ["MLOps"],
        "eval_notes": "纯 CI，非 MLOps。",
        "highlights": [
            "Jenkins / GitLab CI 多语言流水线。",
            "测试门禁与制品库。",
            "不接触模型服务。",
        ],
        "experiences": [
            {
                "company": "宁云工程",
                "title": "CI 工程师",
                "period": "2022.02 - 至今",
                "summary": "交付提效。",
                "bullets": ["多仓模板与缓存加速。"],
            },
            {
                "company": "外包交付组",
                "title": "运维",
                "period": "2021.07 - 2022.01",
                "summary": "环境搭建。",
                "bullets": ["脚本部署。"],
            },
        ],
        "projects": [
            {
                "name": "统一流水线平台",
                "period": "2023.04 - 2024.03",
                "summary": "CI 模板。",
                "bullets": ["Java/Python/前端一站式。"],
            }
        ],
        "education": {
            "school": "南京邮电大学",
            "major": "计算机",
            "degree": "本科",
            "period": "2017.09 - 2021.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Jenkins", "GitLab CI", "Docker", "制品库", "自动化测试门禁"],
        "other": ["期望薪资：22K-28K"],
    },
    {
        "synthetic_key": "mlops_obs_01",
        "category": "MLOps可观测",
        "tags": ["可观测性", "模型监控", "MLOps", "漂移"],
        "status": "待面试",
        "department": "算法/AI平台",
        "name": "蓝柯舟",
        "headline": "MLOps 可观测性｜模型监控｜4年经验",
        "target_position": "MLOps 工程师",
        "years": 4,
        "city": "深圳",
        "phone": "138-7007-0004",
        "email": "lan.kezhou@example.com",
        "availability": "1个月",
        "relevant_for": ["MLOps", "可观测性"],
        "distractor_for": ["DevOps"],
        "eval_notes": "模型漂移监控，工程化相似词。",
        "highlights": [
            "特征/预测分布漂移监控、SLA 告警。",
            "对接 Prometheus 与自定义指标。",
            "不做业务 RAG 应用开发。",
        ],
        "experiences": [
            {
                "company": "模型观测室",
                "title": "MLOps",
                "period": "2022.06 - 至今",
                "summary": "在线模型治理。",
                "bullets": ["漂移检测与自动工单。"],
            },
            {
                "company": "深运维",
                "title": "监控工程师",
                "period": "2021.07 - 2022.05",
                "summary": "基础监控。",
                "bullets": ["Grafana 看板。"],
            },
        ],
        "projects": [
            {
                "name": "模型健康度大盘",
                "period": "2023.07 - 2024.07",
                "summary": "观测产品。",
                "bullets": ["PSI/KL 监控与回滚建议。"],
            }
        ],
        "education": {
            "school": "南方科技大学",
            "major": "计算机",
            "degree": "本科",
            "period": "2017.09 - 2021.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["MLOps", "模型监控", "漂移检测", "Prometheus", "Grafana"],
        "other": ["期望薪资：30K-38K"],
    },
    # ---- 技术招聘 / HR × 3 ----
    {
        "synthetic_key": "hr_tech_01",
        "category": "技术招聘",
        "tags": ["技术招聘", "人才地图", "RAG关键词", "ATS"],
        "status": "已投递",
        "department": "人力资源部",
        "name": "赵晴岚",
        "headline": "技术招聘专家｜AI/后端岗位｜7年经验",
        "target_position": "高级技术招聘专家",
        "years": 7,
        "city": "上海",
        "phone": "138-8008-0001",
        "email": "zhao.qinglan@example.com",
        "availability": "2周内",
        "relevant_for": [],
        "distractor_for": ["RAG", "Python FastAPI Milvus", "Agent"],
        "eval_notes": "文本出现 RAG/AI 但不是技术候选人。",
        "highlights": [
            "长期招聘大模型、RAG、后端与数据岗位。",
            "会拆解 LLM、RAG、Agent、Milvus 等岗位关键词做布尔搜索。",
            "本人不做工程开发，专注人才地图与交付。",
        ],
        "experiences": [
            {
                "company": "启明智联",
                "title": "高级技术招聘",
                "period": "2021.03 - 至今",
                "summary": "算法平台招聘。",
                "bullets": [
                    "年均交付 45+ 技术岗位。",
                    "建设包含 RAG/Milvus 的人才库标签。",
                ],
            },
            {
                "company": "蓝杉咨询",
                "title": "猎头顾问",
                "period": "2018.06 - 2021.02",
                "summary": "中高端寻访。",
                "bullets": ["面试跟进与 Offer 谈判。"],
            },
        ],
        "projects": [
            {
                "name": "AI 岗位人才地图",
                "period": "2023.06 - 2023.12",
                "summary": "招聘运营。",
                "bullets": ["沉淀岗位画像与搜索布尔式。"],
            }
        ],
        "education": {
            "school": "华东师范大学",
            "major": "人力资源管理",
            "degree": "本科",
            "period": "2014.09 - 2018.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["技术招聘", "人才地图", "ATS", "候选人沟通", "Offer 谈判"],
        "other": ["期望薪资：25K-32K"],
    },
    {
        "synthetic_key": "hr_ats_01",
        "category": "招聘运营",
        "tags": ["ATS运营", "招聘运营", "人才库"],
        "status": "AI筛选未通过",
        "department": "人力资源部",
        "name": "苏晚晴",
        "headline": "招聘运营｜ATS / 人才库｜5年经验",
        "target_position": "招聘运营专员",
        "years": 5,
        "city": "北京",
        "phone": "138-8008-0002",
        "email": "su.wanqing@example.com",
        "availability": "随时",
        "relevant_for": [],
        "distractor_for": ["ATS", "RAG"],
        "eval_notes": "ATS 运营非工程。",
        "highlights": [
            "ATS 配置、简历流转与周报。",
            "人才库清洗与激活。",
            "配合技术团队验收搜索功能，但不写代码。",
        ],
        "experiences": [
            {
                "company": "才云 HR",
                "title": "招聘运营",
                "period": "2021.01 - 至今",
                "summary": "ATS 运营。",
                "bullets": ["流程节点配置与权限开通。"],
            },
            {
                "company": "人力共享中心",
                "title": "招聘助理",
                "period": "2019.07 - 2020.12",
                "summary": "简历初筛。",
                "bullets": ["电话邀约。"],
            },
        ],
        "projects": [
            {
                "name": "人才库盘点",
                "period": "2023.08 - 2024.02",
                "summary": "运营项目。",
                "bullets": ["标签清洗与沉默激活。"],
            }
        ],
        "education": {
            "school": "首都经济贸易大学",
            "major": "劳动与社会保障",
            "degree": "本科",
            "period": "2015.09 - 2019.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["ATS运营", "招聘流程", "人才库", "数据周报", "沟通协调"],
        "other": ["期望薪资：14K-20K"],
    },
    {
        "synthetic_key": "hr_map_01",
        "category": "人才地图",
        "tags": ["人才地图", "AI招聘", "竞品调研"],
        "status": "待面试",
        "department": "人力资源部",
        "name": "安景楠",
        "headline": "人才地图顾问｜AI 赛道｜6年经验",
        "target_position": "人才地图顾问",
        "years": 6,
        "city": "深圳",
        "phone": "138-8008-0003",
        "email": "an.jingnan@example.com",
        "availability": "1个月",
        "relevant_for": [],
        "distractor_for": ["RAG", "Agent", "Python FastAPI Milvus"],
        "eval_notes": "大量 AI 关键词但非工程师。",
        "highlights": [
            "绘制大模型、RAG、Agent 赛道公司人才地图。",
            "分析竞品组织与关键趋势。",
            "输出寻访名单，不参与系统研发。",
        ],
        "experiences": [
            {
                "company": "极猎咨询",
                "title": "人才地图顾问",
                "period": "2020.05 - 至今",
                "summary": "AI 赛道。",
                "bullets": [
                    "维护 RAG/向量数据库关键词字典辅助寻访。",
                    "给用人经理讲解岗位难度与市场水位。",
                ],
            },
            {
                "company": "华南猎头",
                "title": "顾问",
                "period": "2018.07 - 2020.04",
                "summary": "互联网招聘。",
                "bullets": ["客户交付。"],
            },
        ],
        "projects": [
            {
                "name": "向量数据库人才地图",
                "period": "2024.01 - 2024.09",
                "summary": "含 Milvus/Qdrant 人才分布调研。",
                "bullets": ["输出城市与公司浓度报告。"],
            }
        ],
        "education": {
            "school": "深圳大学",
            "major": "人力资源管理",
            "degree": "本科",
            "period": "2014.09 - 2018.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["人才地图", "AI招聘", "竞品调研", "寻访", "薪酬调研"],
        "other": ["期望薪资：22K-30K"],
    },
    # ---- 产品 / 项目经理 × 3 ----
    {
        "synthetic_key": "pm_ai_01",
        "category": "AI产品经理",
        "tags": ["AI产品", "RAG产品", "B端"],
        "status": "已投递",
        "department": "产品部",
        "name": "沈予桐",
        "headline": "AI 产品经理｜知识库 / 助手｜5年经验",
        "target_position": "AI 产品经理",
        "years": 5,
        "city": "杭州",
        "phone": "138-9009-0001",
        "email": "shen.yutong@example.com",
        "availability": "2周内",
        "relevant_for": [],
        "distractor_for": ["RAG", "企业知识库问答", "Python FastAPI Milvus"],
        "eval_notes": "岗位语义误召回：AI/RAG 产品非工程师。",
        "highlights": [
            "规划知识库问答与招聘助手功能。",
            "定义评测指标与验收标准。",
            "不写 FastAPI/Milvus 代码。",
        ],
        "experiences": [
            {
                "company": "问知科技",
                "title": "AI 产品经理",
                "period": "2022.04 - 至今",
                "summary": "企业问答产品。",
                "bullets": ["需求拆解与路线图。"],
            },
            {
                "company": "云图软件",
                "title": "产品经理",
                "period": "2019.07 - 2022.03",
                "summary": "B 端 SaaS。",
                "bullets": ["需求文档与验收。"],
            },
        ],
        "projects": [
            {
                "name": "引用式问答",
                "period": "2023.05 - 2024.08",
                "summary": "RAG 产品化。",
                "bullets": ["引用卡片体验与管理员配置。"],
            }
        ],
        "education": {
            "school": "浙江大学",
            "major": "工业设计",
            "degree": "本科",
            "period": "2015.09 - 2019.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["AI产品", "PRD", "用户研究", "指标设计", "B端产品"],
        "other": ["期望薪资：30K-40K"],
    },
    {
        "synthetic_key": "pm_risk_01",
        "category": "风控产品经理",
        "tags": ["风控产品", "策略产品", "反欺诈产品"],
        "status": "AI筛选通过",
        "department": "产品部",
        "name": "魏清澜",
        "headline": "风控产品经理｜反欺诈 / 决策｜6年经验",
        "target_position": "风控产品经理",
        "years": 6,
        "city": "上海",
        "phone": "138-9009-0002",
        "email": "wei.qinglan@example.com",
        "availability": "1个月",
        "relevant_for": [],
        "distractor_for": ["风控实时特征平台"],
        "eval_notes": "风控产品，非特征/算法工程师。",
        "highlights": [
            "反欺诈与信贷决策产品规划。",
            "推动特征/规则需求落地。",
            "不负责 Flink 开发与模型训练。",
        ],
        "experiences": [
            {
                "company": "安衡金科",
                "title": "风控产品经理",
                "period": "2020.08 - 至今",
                "summary": "决策产品。",
                "bullets": ["策略工作台与案件审核台。"],
            },
            {
                "company": "支付公司",
                "title": "产品经理",
                "period": "2018.07 - 2020.07",
                "summary": "风控配置。",
                "bullets": ["规则配置后台。"],
            },
        ],
        "projects": [
            {
                "name": "实时决策工作台",
                "period": "2023.02 - 2024.07",
                "summary": "产品项目。",
                "bullets": ["策略发布与审计需求。"],
            }
        ],
        "education": {
            "school": "上海财经大学",
            "major": "信息管理",
            "degree": "本科",
            "period": "2014.09 - 2018.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["风控产品", "策略配置", "反欺诈", "需求分析", "案件审核"],
        "other": ["期望薪资：32K-42K"],
    },
    {
        "synthetic_key": "pm_saas_01",
        "category": "企业SaaS项目经理",
        "tags": ["项目经理", "SaaS", "交付", "HR系统"],
        "status": "已入职",
        "department": "产品部",
        "name": "东方未",
        "headline": "项目经理｜企业 SaaS 交付｜8年经验",
        "target_position": "项目经理",
        "years": 8,
        "city": "北京 / 上海",
        "phone": "138-9009-0003",
        "email": "dongfang.wei@example.com",
        "availability": "在职",
        "relevant_for": [],
        "distractor_for": ["企业知识库问答", "ATS"],
        "eval_notes": "SaaS 交付项目管理，非技术研发。",
        "highlights": [
            "HR SaaS 实施交付、里程碑与风险管控。",
            "协调客户、研发与实施。",
            "接触过知识库模块上线，但不做 RAG 开发。",
        ],
        "experiences": [
            {
                "company": "云图软件",
                "title": "高级项目经理",
                "period": "2019.01 - 至今",
                "summary": "大型客户交付。",
                "bullets": ["PMO、变更管理与验收。"],
            },
            {
                "company": "实施服务部",
                "title": "实施顾问",
                "period": "2016.07 - 2018.12",
                "summary": "系统上线。",
                "bullets": ["配置与培训。"],
            },
        ],
        "projects": [
            {
                "name": "集团 HR 一体化上线",
                "period": "2023.01 - 2024.06",
                "summary": "交付项目。",
                "bullets": ["含招聘、组织与知识库模块统筹。"],
            }
        ],
        "education": {
            "school": "北京师范大学",
            "major": "信息管理与信息系统",
            "degree": "本科",
            "period": "2012.09 - 2016.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["项目管理", "SaaS交付", "PMP", "风险管理", "客户沟通"],
        "other": ["期望薪资：28K-36K"],
    },
]
