"""Python 后端合成简历。"""

RESUMES = [
    {
        "synthetic_key": "py_fastapi_01",
        "category": "Python后端-FastAPI无向量库",
        "tags": ["Python", "FastAPI", "PostgreSQL", "Celery"],
        "status": "已投递",
        "department": "技术部",
        "name": "梁佑宁",
        "headline": "Python 后端工程师｜FastAPI / PostgreSQL｜5年经验",
        "target_position": "高级 Python 后端工程师",
        "years": 5,
        "city": "北京",
        "phone": "138-2002-0001",
        "email": "liang.youning@example.com",
        "availability": "1个月",
        "relevant_for": ["Python后端", "FastAPI"],
        "distractor_for": ["Python FastAPI Milvus", "RAG"],
        "eval_notes": "干扰1：Python+FastAPI，但无 Milvus/向量库。",
        "highlights": [
            "擅长 FastAPI、异步接口、权限体系与任务队列。",
            "熟悉 PostgreSQL、Redis、Celery，重视测试与接口稳定性。",
            "没有向量数据库与 RAG 相关经验。",
        ],
        "experiences": [
            {
                "company": "北辰云服",
                "title": "高级 Python 后端",
                "period": "2021.08 - 至今",
                "summary": "招聘 ATS 后端。",
                "bullets": [
                    "FastAPI 建设候选人状态机、面试预约与权限校验。",
                    "Celery 处理简历解析异步任务，接口超时率降至 1%。",
                    "未引入 Milvus 或其他向量库。",
                ],
            },
            {
                "company": "瑞木科技",
                "title": "后端工程师",
                "period": "2019.07 - 2021.07",
                "summary": "企业协同后端。",
                "bullets": ["SQLAlchemy + PostgreSQL API 开发。"],
            },
        ],
        "projects": [
            {
                "name": "招聘消息网关",
                "period": "2023.02 - 2024.01",
                "summary": "邮件/站内通知。",
                "bullets": ["幂等键与重试，避免重复通知。"],
            }
        ],
        "education": {
            "school": "北京邮电大学",
            "major": "软件工程",
            "degree": "本科",
            "period": "2015.09 - 2019.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Python", "FastAPI", "PostgreSQL", "Redis", "Celery", "Docker"],
        "other": ["期望薪资：30K-38K"],
    },
    {
        "synthetic_key": "py_fastapi_02",
        "category": "Python后端-FastAPI无向量库",
        "tags": ["Python", "FastAPI", "权限", "微服务"],
        "status": "AI筛选通过",
        "department": "算法/AI平台",
        "name": "何景行",
        "headline": "Python 后端工程师｜FastAPI / RBAC｜4年经验",
        "target_position": "Python 后端工程师",
        "years": 4,
        "city": "杭州",
        "phone": "138-2002-0002",
        "email": "he.jingxing@example.com",
        "availability": "2周内",
        "relevant_for": ["Python后端", "FastAPI", "权限系统"],
        "distractor_for": ["Python FastAPI Milvus"],
        "eval_notes": "干扰：FastAPI + 权限，无向量检索。",
        "highlights": [
            "熟悉 FastAPI、JWT/RBAC、多租户与审计日志。",
            "能建设可测试的服务层与 Schema 约束。",
            "了解 AI 产品对接，但不负责检索与 Embedding。",
        ],
        "experiences": [
            {
                "company": "杭易科技",
                "title": "后端工程师",
                "period": "2022.03 - 至今",
                "summary": "企业 SaaS 权限中心。",
                "bullets": [
                    "基于 FastAPI 实现角色、权限码与资源范围校验。",
                    "统一异常码与 OpenAPI 文档。",
                ],
            },
            {
                "company": "乐岛网络",
                "title": "Python 开发",
                "period": "2021.07 - 2022.02",
                "summary": "内容社区。",
                "bullets": ["API 与后台管理。"],
            },
        ],
        "projects": [
            {
                "name": "组织架构与用户管理改造",
                "period": "2024.04 - 2024.12",
                "summary": "RBAC 重构。",
                "bullets": ["部门范围与资源级权限策略落地。"],
            }
        ],
        "education": {
            "school": "杭州电子科技大学",
            "major": "计算机",
            "degree": "本科",
            "period": "2017.09 - 2021.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Python", "FastAPI", "RBAC", "PostgreSQL", "Redis", "OpenAPI"],
        "other": ["期望薪资：28K-35K"],
    },
    {
        "synthetic_key": "py_fastapi_03",
        "category": "Python后端-FastAPI无向量库",
        "tags": ["Python", "FastAPI", "ATS", "任务队列"],
        "status": "已入职",
        "department": "技术部",
        "name": "潘彦博",
        "headline": "Python 后端工程师｜ATS / FastAPI｜6年经验",
        "target_position": "资深 Python 后端",
        "years": 6,
        "city": "深圳",
        "phone": "138-2002-0003",
        "email": "pan.yanbo@example.com",
        "availability": "在职可谈",
        "relevant_for": ["Python后端", "FastAPI", "ATS"],
        "distractor_for": ["Python FastAPI Milvus", "RAG"],
        "eval_notes": "干扰：招聘系统 FastAPI 后端，无向量库。",
        "highlights": [
            "长期做招聘 ATS 后端，熟悉候选人状态流转与面试排期。",
            "FastAPI + Celery 处理异步解析，但不做语义检索。",
            "能与算法同学对接评分结果落库，不参与模型部署。",
        ],
        "experiences": [
            {
                "company": "招易通",
                "title": "资深后端",
                "period": "2020.05 - 至今",
                "summary": "ATS 核心服务。",
                "bullets": [
                    "候选人、职位、面试表设计与 API。",
                    "对接 AI 评分回调，写入综合分与状态。",
                ],
            },
            {
                "company": "南海研发",
                "title": "后端工程师",
                "period": "2018.07 - 2020.04",
                "summary": "中后台。",
                "bullets": ["Flask 迁移 FastAPI。"],
            },
        ],
        "projects": [
            {
                "name": "简历解析任务中心",
                "period": "2023.01 - 2023.12",
                "summary": "异步任务。",
                "bullets": ["任务归属校验与可追溯 task_id。"],
            }
        ],
        "education": {
            "school": "中山大学",
            "major": "软件工程",
            "degree": "本科",
            "period": "2014.09 - 2018.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Python", "FastAPI", "Celery", "PostgreSQL", "ATS", "状态机"],
        "other": ["期望薪资：34K-42K"],
    },
    {
        "synthetic_key": "py_django_01",
        "category": "Python后端-Django",
        "tags": ["Python", "Django", "MySQL", "后台"],
        "status": "AI筛选未通过",
        "department": "技术部",
        "name": "郑皓文",
        "headline": "Python 后端工程师｜Django / MySQL｜5年经验",
        "target_position": "Python 后端工程师",
        "years": 5,
        "city": "成都",
        "phone": "138-2002-0004",
        "email": "zheng.haowen@example.com",
        "availability": "1个月",
        "relevant_for": ["Python后端", "Django"],
        "distractor_for": ["Python FastAPI Milvus"],
        "eval_notes": "干扰：Python 后端但 Django 栈。",
        "highlights": [
            "熟悉 Django ORM、Admin、权限与后台中台开发。",
            "有电商库存与售后经验。",
            "未使用 FastAPI 与向量数据库。",
        ],
        "experiences": [
            {
                "company": "蜀川电商",
                "title": "后端工程师",
                "period": "2021.02 - 至今",
                "summary": "交易后台。",
                "bullets": ["Django 开发订单后台与导出任务。"],
            },
            {
                "company": "米粒互联",
                "title": "Python 开发",
                "period": "2019.07 - 2021.01",
                "summary": "内容 CMS。",
                "bullets": ["Django REST Framework。"],
            },
        ],
        "projects": [
            {
                "name": "运营后台重构",
                "period": "2023.06 - 2024.03",
                "summary": "后台性能优化。",
                "bullets": ["慢查询与权限校验优化。"],
            }
        ],
        "education": {
            "school": "四川大学",
            "major": "计算机",
            "degree": "本科",
            "period": "2015.09 - 2019.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Python", "Django", "DRF", "MySQL", "Redis", "Celery"],
        "other": ["期望薪资：25K-32K"],
    },
    {
        "synthetic_key": "py_flask_01",
        "category": "Python后端-Flask",
        "tags": ["Python", "Flask", "SQLAlchemy", "API"],
        "status": "已投递",
        "department": "技术部",
        "name": "冯子墨",
        "headline": "Python 后端工程师｜Flask / SQLAlchemy｜4年经验",
        "target_position": "Python 后端工程师",
        "years": 4,
        "city": "武汉",
        "phone": "138-2002-0005",
        "email": "feng.zimo@example.com",
        "availability": "2周内",
        "relevant_for": ["Python后端", "Flask"],
        "distractor_for": ["Python FastAPI Milvus"],
        "eval_notes": "干扰：Flask 后端，无 FastAPI/Milvus。",
        "highlights": [
            "熟悉 Flask 蓝图、SQLAlchemy 与 RESTful 设计。",
            "做过数据导入与报表导出。",
            "无 RAG/向量检索经验。",
        ],
        "experiences": [
            {
                "company": "江城数科",
                "title": "后端工程师",
                "period": "2022.01 - 至今",
                "summary": "企业内部系统。",
                "bullets": ["Flask API、登录鉴权与报表导出。"],
            },
            {
                "company": "光谷软件",
                "title": "初级开发",
                "period": "2021.07 - 2021.12",
                "summary": "外包交付。",
                "bullets": ["CRUD 接口。"],
            },
        ],
        "projects": [
            {
                "name": "考勤与审批系统",
                "period": "2023.03 - 2023.12",
                "summary": "内部工具。",
                "bullets": ["流程状态落库与消息通知。"],
            }
        ],
        "education": {
            "school": "华中科技大学",
            "major": "软件工程",
            "degree": "本科",
            "period": "2017.09 - 2021.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Python", "Flask", "SQLAlchemy", "MySQL", "RESTful"],
        "other": ["期望薪资：22K-28K"],
    },
    {
        "synthetic_key": "py_data_platform_01",
        "category": "Python数据平台",
        "tags": ["Python", "Airflow", "数据平台", "Kafka"],
        "status": "待面试",
        "department": "数据/风控",
        "name": "蒋一帆",
        "headline": "数据平台工程师｜Python / Airflow / Kafka｜5年经验",
        "target_position": "数据平台工程师",
        "years": 5,
        "city": "上海",
        "phone": "138-2002-0006",
        "email": "jiang.yifan@example.com",
        "availability": "1个月",
        "relevant_for": ["数据平台", "ETL"],
        "distractor_for": ["风控实时特征平台", "Python FastAPI Milvus"],
        "eval_notes": "干扰：Python 数据平台，非风控实时特征。",
        "highlights": [
            "熟悉 Airflow 调度、Kafka 采集与离线数仓同步。",
            "擅长 Python 数据任务与质量监控。",
            "不做在线特征服务与向量检索。",
        ],
        "experiences": [
            {
                "company": "申江数据",
                "title": "数据平台工程师",
                "period": "2021.05 - 至今",
                "summary": "离线数据管道。",
                "bullets": [
                    "Airflow DAG 管理日批次同步，SLA 告警。",
                    "Kafka 消费日志写入 Hive/Iceberg。",
                ],
            },
            {
                "company": "数脉科技",
                "title": "ETL 开发",
                "period": "2019.07 - 2021.04",
                "summary": "数据集成。",
                "bullets": ["Python ETL 与数据校验。"],
            },
        ],
        "projects": [
            {
                "name": "日志入仓平台",
                "period": "2023.04 - 2024.02",
                "summary": "Kafka to Lake。",
                "bullets": ["分区策略与回溯补数。"],
            }
        ],
        "education": {
            "school": "同济大学",
            "major": "计算机",
            "degree": "本科",
            "period": "2015.09 - 2019.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Python", "Airflow", "Kafka", "Hive", "ETL", "数据质量"],
        "other": ["期望薪资：30K-38K"],
    },
    {
        "synthetic_key": "py_data_platform_02",
        "category": "Python数据平台",
        "tags": ["Python", "Spark", "数仓", "指标"],
        "status": "AI筛选未通过",
        "department": "数据/风控",
        "name": "许鸣泽",
        "headline": "数据开发工程师｜Python / Spark｜4年经验",
        "target_position": "数据开发工程师",
        "years": 4,
        "city": "北京",
        "phone": "138-2002-0007",
        "email": "xu.mingze@example.com",
        "availability": "2周内",
        "relevant_for": ["数据工程", "Spark"],
        "distractor_for": ["风控实时特征平台"],
        "eval_notes": "干扰：Spark 离线开发，非实时风控特征。",
        "highlights": [
            "Spark 批处理、指标口径与主题宽表建设。",
            "熟悉 Python UDF 与任务调优。",
            "无 Flink 实时特征平台经验。",
        ],
        "experiences": [
            {
                "company": "京北数据",
                "title": "数据开发",
                "period": "2022.04 - 至今",
                "summary": "业务主题宽表。",
                "bullets": ["Spark SQL 构建招聘漏斗指标。"],
            },
            {
                "company": "观远咨询",
                "title": "数据分析工程师",
                "period": "2021.07 - 2022.03",
                "summary": "报表支撑。",
                "bullets": ["Python 分析脚本。"],
            },
        ],
        "projects": [
            {
                "name": "招聘主题数仓",
                "period": "2023.07 - 2024.06",
                "summary": "离线主题模型。",
                "bullets": ["候选人漏斗与渠道归因。"],
            }
        ],
        "education": {
            "school": "北京理工大学",
            "major": "数据科学",
            "degree": "本科",
            "period": "2017.09 - 2021.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Python", "Spark", "SQL", "数仓", "指标口径"],
        "other": ["期望薪资：26K-33K"],
    },
    {
        "synthetic_key": "py_payment_01",
        "category": "Python支付交易后端",
        "tags": ["Python", "支付", "交易", "FastAPI"],
        "status": "已投递",
        "department": "技术部",
        "name": "秦嘉懿",
        "headline": "Python 支付后端｜交易 / 清算 / FastAPI｜6年经验",
        "target_position": "支付后端工程师",
        "years": 6,
        "city": "上海 / 杭州",
        "phone": "138-2002-0008",
        "email": "qin.jiayi@example.com",
        "availability": "1个月",
        "relevant_for": ["支付后端", "交易系统"],
        "distractor_for": ["风控实时特征平台", "Python FastAPI Milvus"],
        "eval_notes": "干扰：支付/交易后端（含 FastAPI），用于风控实时特征等查询误召回。",
        "highlights": [
            "长期负责支付下单、回调、退款与对账，强调幂等与资金安全。",
            "熟悉 FastAPI、PostgreSQL、Kafka、Redis。",
            "接触过风控调用，但本人不做特征平台与评分卡。",
        ],
        "experiences": [
            {
                "company": "汇川支付",
                "title": "资深后端",
                "period": "2020.08 - 至今",
                "summary": "支付核心链路。",
                "bullets": [
                    "FastAPI 支付网关，渠道回调幂等与超时补偿。",
                    "Kafka 解耦清算与账务流水。",
                ],
            },
            {
                "company": "尚银科技",
                "title": "后端工程师",
                "period": "2018.07 - 2020.07",
                "summary": "账户系统。",
                "bullets": ["余额、冻结与出入金。"],
            },
        ],
        "projects": [
            {
                "name": "统一对账平台",
                "period": "2023.01 - 2024.01",
                "summary": "渠道对账。",
                "bullets": ["日终对账差异定位。"],
            }
        ],
        "education": {
            "school": "华东师范大学",
            "major": "软件工程",
            "degree": "本科",
            "period": "2014.09 - 2018.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Python", "FastAPI", "支付", "对账", "Kafka", "Redis", "幂等"],
        "other": ["期望薪资：36K-45K"],
    },
]
