"""风控算法 / 数据科学合成简历。"""

RESUMES = [
    {
        "synthetic_key": "risk_realtime_01",
        "category": "风控实时特征",
        "tags": ["风控", "Flink", "Kafka", "特征平台", "实时决策"],
        "status": "AI筛选通过",
        "department": "数据/风控",
        "name": "程亦安",
        "headline": "风控算法工程师｜实时特征平台 / 反欺诈｜6年经验",
        "target_position": "风控算法工程师",
        "years": 6,
        "city": "上海 / 杭州",
        "phone": "138-4004-0001",
        "email": "cheng.yian@example.com",
        "availability": "1个月",
        "relevant_for": ["风控实时特征平台", "反欺诈", "有风控平台经验的后端工程师"],
        "distractor_for": [],
        "eval_notes": "强相关：反欺诈 + Flink/Kafka + 特征平台 + 在线决策。",
        "highlights": [
            "负责反欺诈实时决策，建设 Flink 实时特征与在线打分服务。",
            "熟悉 Kafka、特征平台、规则引擎与模型服务化。",
            "关注误杀率、召回率与特征稳定性。",
        ],
        "experiences": [
            {
                "company": "安衡金科",
                "title": "高级风控算法",
                "period": "2021.02 - 至今",
                "summary": "交易反欺诈。",
                "bullets": [
                    "Flink 计算设备行为实时特征，写入在线 KV。",
                    "特征平台统一离在线口径，支撑秒级决策。",
                    "对接规则引擎与模型分，形成可解释决策理由。",
                ],
            },
            {
                "company": "慧策数据",
                "title": "算法工程师",
                "period": "2018.07 - 2021.01",
                "summary": "信贷评分。",
                "bullets": ["评分卡与特征监控。"],
            },
        ],
        "projects": [
            {
                "name": "实时反欺诈决策平台",
                "period": "2023.03 - 2024.12",
                "summary": "在线决策。",
                "bullets": ["端到端延迟 P99 < 80ms。"],
            }
        ],
        "education": {
            "school": "复旦大学",
            "major": "统计学",
            "degree": "硕士",
            "period": "2015.09 - 2018.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["风控", "反欺诈", "Flink", "Kafka", "特征平台", "实时决策", "Python"],
        "other": ["期望薪资：40K-55K"],
    },
    {
        "synthetic_key": "risk_feature_01",
        "category": "风控特征平台",
        "tags": ["特征平台", "Flink", "在线特征", "风控"],
        "status": "待面试",
        "department": "算法/AI平台",
        "name": "罗景晖",
        "headline": "特征平台工程师｜风控在线特征｜5年经验",
        "target_position": "特征平台工程师",
        "years": 5,
        "city": "北京",
        "phone": "138-4004-0002",
        "email": "luo.jinghui@example.com",
        "availability": "2周内",
        "relevant_for": ["风控实时特征平台"],
        "distractor_for": [],
        "eval_notes": "强相关：实时特征平台核心建设者。",
        "highlights": [
            "专注特征注册、血缘、点查服务与离在线一致性。",
            "熟悉 Flink、Redis、特征 DSL。",
            "服务信贷与支付风控场景。",
        ],
        "experiences": [
            {
                "company": "启衡科技",
                "title": "特征平台工程师",
                "period": "2021.06 - 至今",
                "summary": "通用特征平台。",
                "bullets": [
                    "建设实时特征计算作业模板与回填能力。",
                    "提供高可用特征点查 API。",
                ],
            },
            {
                "company": "数方",
                "title": "数据开发",
                "period": "2019.07 - 2021.05",
                "summary": "离线特征。",
                "bullets": ["Hive 特征宽表。"],
            },
        ],
        "projects": [
            {
                "name": "统一特征平台 2.0",
                "period": "2023.01 - 2024.09",
                "summary": "离在线一体。",
                "bullets": ["特征 SLA 与漂移告警。"],
            }
        ],
        "education": {
            "school": "中国人民大学",
            "major": "应用统计",
            "degree": "硕士",
            "period": "2016.09 - 2019.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["特征平台", "Flink", "Kafka", "Redis", "风控", "特征血缘"],
        "other": ["期望薪资：38K-48K"],
    },
    {
        "synthetic_key": "risk_fraud_01",
        "category": "反欺诈算法",
        "tags": ["反欺诈", "图模型", "风控", "实时决策"],
        "status": "已投递",
        "department": "数据/风控",
        "name": "韩若汐",
        "headline": "反欺诈算法工程师｜图模型 / 设备指纹｜5年经验",
        "target_position": "反欺诈算法工程师",
        "years": 5,
        "city": "深圳",
        "phone": "138-4004-0003",
        "email": "han.ruoxi@example.com",
        "availability": "1个月",
        "relevant_for": ["风控实时特征平台", "反欺诈"],
        "distractor_for": [],
        "eval_notes": "强相关：反欺诈 + 图模型 + 实时决策。",
        "highlights": [
            "设备/团伙反欺诈，熟悉图模型与关系网络挖掘。",
            "特征接入实时决策链路。",
            "能与策略同学共建规则与模型。",
        ],
        "experiences": [
            {
                "company": "安盾互金",
                "title": "反欺诈算法",
                "period": "2021.08 - 至今",
                "summary": "注册登录与交易环节。",
                "bullets": [
                    "图嵌入识别团伙，结合规则实时拦截。",
                    "维护实时特征依赖与策略灰度。",
                ],
            },
            {
                "company": "深数",
                "title": "算法工程师",
                "period": "2019.07 - 2021.07",
                "summary": "异常检测。",
                "bullets": ["无监督异常分数。"],
            },
        ],
        "projects": [
            {
                "name": "团伙识别实时决策",
                "period": "2023.05 - 2024.10",
                "summary": "图 + 规则。",
                "bullets": ["误杀率下降 18%。"],
            }
        ],
        "education": {
            "school": "中山大学",
            "major": "计算机",
            "degree": "硕士",
            "period": "2016.09 - 2019.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["反欺诈", "图模型", "实时决策", "Python", "Neo4j", "风控策略"],
        "other": ["期望薪资：36K-46K"],
    },
    {
        "synthetic_key": "risk_scorecard_01",
        "category": "传统评分卡",
        "tags": ["评分卡", "信用风险", "逻辑回归", "风控"],
        "status": "AI筛选未通过",
        "department": "数据/风控",
        "name": "杜澄明",
        "headline": "信贷风控算法｜评分卡 / 授信｜7年经验",
        "target_position": "信贷风控算法",
        "years": 7,
        "city": "北京",
        "phone": "138-4004-0004",
        "email": "du.chengming@example.com",
        "availability": "2周内",
        "relevant_for": ["信贷风控", "评分卡"],
        "distractor_for": ["风控实时特征平台"],
        "eval_notes": "干扰：传统信用评分，无实时特征平台。",
        "highlights": [
            "A/B/C 卡评分卡建模、分箱、PSI 监控。",
            "熟悉逻辑回归与规则组合授信。",
            "以离线批次为主，未建设 Flink 实时特征平台。",
        ],
        "experiences": [
            {
                "company": "宏信消金",
                "title": "风控算法专家",
                "period": "2019.03 - 至今",
                "summary": "授信定价。",
                "bullets": [
                    "申请评分卡与额度策略。",
                    "月度模型监控与复训。",
                ],
            },
            {
                "company": "银杏银行科技",
                "title": "风险分析",
                "period": "2017.07 - 2019.02",
                "summary": "贷后。",
                "bullets": ["滚动率与迁徙分析。"],
            },
        ],
        "projects": [
            {
                "name": "申请评分卡重构",
                "period": "2023.01 - 2023.12",
                "summary": "离线建模。",
                "bullets": ["KS/AUC 提升与策略联动。"],
            }
        ],
        "education": {
            "school": "对外经济贸易大学",
            "major": "金融工程",
            "degree": "硕士",
            "period": "2014.09 - 2017.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["评分卡", "信用风险", "逻辑回归", "PSI", "授信策略", "Python"],
        "other": ["期望薪资：35K-45K"],
    },
    {
        "synthetic_key": "risk_credit_01",
        "category": "信贷风控策略",
        "tags": ["信贷风控", "策略", "额度", "审批"],
        "status": "已投递",
        "department": "数据/风控",
        "name": "方予安",
        "headline": "信贷风控策略｜审批 / 额度｜5年经验",
        "target_position": "风控策略经理",
        "years": 5,
        "city": "上海",
        "phone": "138-4004-0005",
        "email": "fang.yuan@example.com",
        "availability": "1个月",
        "relevant_for": ["信贷风控"],
        "distractor_for": ["风控实时特征平台"],
        "eval_notes": "干扰：策略侧，非实时特征工程。",
        "highlights": [
            "审批策略、额度分层与拒绝码体系。",
            "熟悉策略实验与贷后反馈闭环。",
            "依赖特征平台输出，但不开发实时计算。",
        ],
        "experiences": [
            {
                "company": "浦江消费金融",
                "title": "风控策略",
                "period": "2021.05 - 至今",
                "summary": "审批策略。",
                "bullets": ["规则编排与通过率/坏账平衡。"],
            },
            {
                "company": "信审外包",
                "title": "信审专员",
                "period": "2019.07 - 2021.04",
                "summary": "人工信审。",
                "bullets": ["资料核实。"],
            },
        ],
        "projects": [
            {
                "name": "额度分层策略",
                "period": "2023.06 - 2024.05",
                "summary": "客群分层。",
                "bullets": ["新客与复贷差异化额度。"],
            }
        ],
        "education": {
            "school": "上海财经大学",
            "major": "风险管理",
            "degree": "本科",
            "period": "2015.09 - 2019.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["信贷风控", "审批策略", "额度管理", "A/B 实验", "坏账分析"],
        "other": ["期望薪资：28K-36K"],
    },
    {
        "synthetic_key": "risk_graph_01",
        "category": "风控图算法",
        "tags": ["图模型", "风控", "知识图谱", "关系网络"],
        "status": "AI筛选通过",
        "department": "算法/AI平台",
        "name": "谢清衡",
        "headline": "图算法工程师｜风控图谱｜4年经验",
        "target_position": "图算法工程师",
        "years": 4,
        "city": "杭州",
        "phone": "138-4004-0006",
        "email": "xie.qingheng@example.com",
        "availability": "2周内",
        "relevant_for": ["图模型", "反欺诈"],
        "distractor_for": ["风控实时特征平台"],
        "eval_notes": "相关偏图模型；实时特征平台不是主职责。",
        "highlights": [
            "风控知识图谱、社区发现与关联查询。",
            "熟悉 Neo4j / 自研图引擎。",
            "特征结果可供决策调用，但平台工程非本人。",
        ],
        "experiences": [
            {
                "company": "杭盾科技",
                "title": "图算法工程师",
                "period": "2022.03 - 至今",
                "summary": "反欺诈图谱。",
                "bullets": ["构建人-设备-地址关系图谱。"],
            },
            {
                "company": "云图实验室",
                "title": "算法工程师",
                "period": "2021.07 - 2022.02",
                "summary": "图表示学习。",
                "bullets": ["GNN 实验。"],
            },
        ],
        "projects": [
            {
                "name": "关联风险查询服务",
                "period": "2023.08 - 2024.08",
                "summary": "图谱检索。",
                "bullets": ["一度二度关联解释。"],
            }
        ],
        "education": {
            "school": "浙江大学",
            "major": "计算机",
            "degree": "硕士",
            "period": "2018.09 - 2021.06",
            "note": "方向：图数据挖掘",
            "bullets": [],
        },
        "skills": ["图模型", "GNN", "Neo4j", "反欺诈", "Python", "关系网络"],
        "other": ["期望薪资：32K-42K"],
    },
    {
        "synthetic_key": "ds_hpc_01",
        "category": "数据科学-近似空结果",
        "tags": ["算法工程师", "高性能计算", "编译优化", "PyTorch"],
        "status": "AI筛选未通过",
        "department": "算法/AI平台",
        "name": "白航深",
        "headline": "算法工程师｜模型训练加速 / 编译优化｜5年经验",
        "target_position": "算法工程师",
        "years": 5,
        "city": "北京",
        "phone": "138-4004-0007",
        "email": "bai.hangshen@example.com",
        "availability": "1个月",
        "relevant_for": [],
        "distractor_for": ["具备量子计算编译器生产实践经验的人"],
        "eval_notes": "空结果干扰：有编译优化/高性能计算近似文本，但无量子/RTL/手术机器人。",
        "highlights": [
            "算法工程师，专注深度学习训练吞吐与推理加速。",
            "做过算子融合、编译优化试验与高性能计算集群调度。",
            "业务专注 CV/NLP 训推性能，不含量子、芯片硬件验证或医疗机器人方向经验。",
        ],
        "experiences": [
            {
                "company": "极算实验室",
                "title": "算法工程师",
                "period": "2021.01 - 至今",
                "summary": "训练加速。",
                "bullets": [
                    "PyTorch 分布式训练与混合精度。",
                    "探索编译优化降低 kernel launch 开销。",
                    "高性能计算集群上的任务排队与资源隔离。",
                ],
            },
            {
                "company": "中科视算",
                "title": "初级算法",
                "period": "2019.07 - 2020.12",
                "summary": "CV 模型。",
                "bullets": ["目标检测训练。"],
            },
        ],
        "projects": [
            {
                "name": "训推性能优化专项",
                "period": "2023.04 - 2024.06",
                "summary": "吞吐提升。",
                "bullets": ["端到端训练时延下降 25%。"],
            }
        ],
        "education": {
            "school": "中国科学院大学",
            "major": "计算机",
            "degree": "硕士",
            "period": "2016.09 - 2019.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["算法工程师", "PyTorch", "编译优化", "高性能计算", "分布式训练"],
        "other": ["期望薪资：35K-45K"],
    },
    {
        "synthetic_key": "risk_decision_01",
        "category": "实时决策引擎",
        "tags": ["实时决策", "规则引擎", "风控", "Kafka"],
        "status": "已入职",
        "department": "数据/风控",
        "name": "袁知行",
        "headline": "实时决策工程师｜规则引擎 / 风控｜6年经验",
        "target_position": "实时决策工程师",
        "years": 6,
        "city": "深圳 / 上海",
        "phone": "138-4004-0008",
        "email": "yuan.zhixing@example.com",
        "availability": "在职",
        "relevant_for": ["风控实时特征平台", "实时决策"],
        "distractor_for": [],
        "eval_notes": "强相关：在线决策 + Kafka；与特征平台紧密协作。",
        "highlights": [
            "在线规则引擎、决策流编排与灰度发布。",
            "对接实时特征点查与模型分服务。",
            "熟悉可观测性与策略回滚。",
        ],
        "experiences": [
            {
                "company": "决策云",
                "title": "实时决策工程师",
                "period": "2020.06 - 至今",
                "summary": "支付/信贷决策。",
                "bullets": [
                    "Kafka 触发决策、特征拉取与结果回写。",
                    "规则版本管理与影子流量。",
                ],
            },
            {
                "company": "易付通",
                "title": "Java 后端",
                "period": "2018.07 - 2020.05",
                "summary": "风控接入。",
                "bullets": ["同步调用治理。"],
            },
        ],
        "projects": [
            {
                "name": "统一决策中枢",
                "period": "2023.02 - 2024.11",
                "summary": "多场景决策。",
                "bullets": ["登录/交易/提现统一编排。"],
            }
        ],
        "education": {
            "school": "哈尔滨工业大学",
            "major": "软件工程",
            "degree": "本科",
            "period": "2014.09 - 2018.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["实时决策", "规则引擎", "Kafka", "风控", "灰度", "Java"],
        "other": ["期望薪资：38K-48K"],
    },
]
