"""RAG / 大模型应用相关合成简历。"""

RESUMES = [
    {
        "synthetic_key": "rag_fullstack_01",
        "category": "RAG全栈",
        "tags": ["Python", "FastAPI", "Milvus", "RAG", "LangChain"],
        "status": "AI筛选通过",
        "department": "算法/AI平台",
        "name": "周启航",
        "headline": "RAG / 大模型应用工程师｜Python / FastAPI / Milvus｜5年经验",
        "target_position": "大模型应用工程师",
        "years": 5,
        "city": "上海 / 杭州",
        "phone": "138-1001-0001",
        "email": "zhou.qihang@example.com",
        "availability": "2周内",
        "relevant_for": ["Python FastAPI Milvus", "企业知识库问答", "RAG"],
        "distractor_for": [],
        "eval_notes": "强相关：同时具备 Python+FastAPI+Milvus，并有向量检索线上项目。",
        "highlights": [
            "熟悉文档切片、Embedding、Milvus 混合检索、重排序与答案生成全链路，能独立闭环评测。",
            "熟练使用 Python、FastAPI、LangChain、Milvus，能将检索服务工程化为稳定 API。",
            "有企业知识库问答与人才语义检索落地经验，关注召回率、延迟与幻觉控制。",
        ],
        "experiences": [
            {
                "company": "星澜智能",
                "title": "大模型应用工程师",
                "period": "2023.03 - 至今",
                "summary": "负责企业知识库与候选人语义检索后端。",
                "bullets": [
                    "基于 Milvus 构建向量集合，落地 dense + BM25 混合检索，并支持部门/状态过滤。",
                    "使用 FastAPI 封装检索与引用返回接口，P95 延迟控制在 420ms 内。",
                    "搭建离线评测集，覆盖精确技能、语义近义与空结果拒答场景。",
                ],
            },
            {
                "company": "云禾科技",
                "title": "Python 后端工程师",
                "period": "2020.07 - 2023.02",
                "summary": "负责中后台 API 与任务队列。",
                "bullets": [
                    "使用 FastAPI + PostgreSQL 建设文档管理与权限模块。",
                    "推进异步解析任务与幂等设计，保障高峰期稳定性。",
                ],
            },
        ],
        "projects": [
            {
                "name": "企业制度知识库问答",
                "period": "2024.05 - 2025.01",
                "summary": "面向全员的制度检索与引用问答。",
                "bullets": [
                    "完成 PDF/Markdown 抽取、分块、向量化与 Milvus 入库。",
                    "用 LangChain 编排检索-重排-生成，并输出可追溯引用片段。",
                ],
            }
        ],
        "education": {
            "school": "复旦大学",
            "major": "计算机科学与技术",
            "degree": "硕士",
            "period": "2017.09 - 2020.06",
            "note": "研究方向：信息检索与自然语言处理",
            "bullets": ["GPA 3.6/4.0"],
        },
        "skills": ["Python", "FastAPI", "Milvus", "RAG", "LangChain", "Embedding", "PostgreSQL", "Docker"],
        "other": ["英语 CET-6", "期望薪资：35K-45K"],
    },
    {
        "synthetic_key": "rag_fullstack_02",
        "category": "RAG全栈",
        "tags": ["Python", "FastAPI", "Milvus", "RAG", "Rerank"],
        "status": "待面试",
        "department": "算法/AI平台",
        "name": "韩沐阳",
        "headline": "大模型检索工程师｜RAG / Milvus / FastAPI｜4年经验",
        "target_position": "RAG 应用工程师",
        "years": 4,
        "city": "北京",
        "phone": "138-1001-0002",
        "email": "han.muyang@example.com",
        "availability": "1个月",
        "relevant_for": ["Python FastAPI Milvus", "企业知识库问答", "RAG"],
        "distractor_for": [],
        "eval_notes": "强相关：完整 RAG 链路 + FastAPI 服务化 + Milvus。",
        "highlights": [
            "擅长向量召回、交叉编码器重排与拒答策略，能把 RAG 从 PoC 推到生产。",
            "熟悉 Python、FastAPI、Milvus、Redis，具备检索服务容量规划经验。",
            "理解权限隔离与审计，不让语义检索绕过业务数据权限。",
        ],
        "experiences": [
            {
                "company": "北泽 AI",
                "title": "大模型应用工程师",
                "period": "2022.11 - 至今",
                "summary": "负责客服知识库与内部问答平台。",
                "bullets": [
                    "使用 Milvus 实现多知识库路由检索，支持租户隔离。",
                    "FastAPI 微服务对接工单系统，沉淀引用审计日志。",
                    "引入 Rerank 与规则拒答，人工核验通过率提升至 84%。",
                ],
            },
            {
                "company": "启元软件",
                "title": "后端开发",
                "period": "2021.07 - 2022.10",
                "summary": "Python Web 开发。",
                "bullets": ["使用 FastAPI 开发配置中心与网关鉴权。"],
            },
        ],
        "projects": [
            {
                "name": "候选人语义检索评测平台",
                "period": "2024.08 - 2025.02",
                "summary": "为招聘助手构建检索评测闭环。",
                "bullets": [
                    "把画像写入 Milvus，对比 BM25 / dense / hybrid 指标。",
                    "沉淀 query 集：精确技能、语义近义、跨栈干扰与空结果。",
                ],
            }
        ],
        "education": {
            "school": "北京航空航天大学",
            "major": "软件工程",
            "degree": "本科",
            "period": "2017.09 - 2021.06",
            "note": "主修课程：机器学习、数据库、分布式系统",
            "bullets": ["校级优秀毕业生"],
        },
        "skills": ["Python", "FastAPI", "Milvus", "RAG", "Rerank", "Redis", "评测集", "权限过滤"],
        "other": ["英语 CET-6", "期望薪资：32K-42K"],
    },
    {
        "synthetic_key": "rag_fullstack_03",
        "category": "RAG全栈",
        "tags": ["Python", "FastAPI", "Milvus", "LangGraph", "Agent"],
        "status": "已投递",
        "department": "算法/AI平台",
        "name": "唐书尧",
        "headline": "智能体与 RAG 工程师｜LangGraph / FastAPI / Milvus｜6年经验",
        "target_position": "Agent / RAG 工程师",
        "years": 6,
        "city": "深圳 / 上海",
        "phone": "138-1001-0003",
        "email": "tang.shuyao@example.com",
        "availability": "随时",
        "relevant_for": ["Python FastAPI Milvus", "企业知识库问答", "RAG", "Agent"],
        "distractor_for": [],
        "eval_notes": "强相关：Agent + RAG，且后端用 FastAPI，向量库为 Milvus。",
        "highlights": [
            "同时具备 RAG 检索与 Agent 编排能力，能落地工具调用与多轮规划。",
            "熟悉 Python、FastAPI、Milvus、LangGraph，能把智能体接入现有业务系统。",
            "关注工具权限、轨迹日志与成本，避免无边界自动操作。",
        ],
        "experiences": [
            {
                "company": "深海星图",
                "title": "高级大模型工程师",
                "period": "2022.05 - 至今",
                "summary": "负责招聘助手与制度问答 Agent。",
                "bullets": [
                    "Milvus 人才库检索 + FastAPI Tool 封装，支持自然语言找人。",
                    "用 LangGraph 编排检索、澄清、引用与拒答节点。",
                    "建立 prompt/版本与评测回归流水线。",
                ],
            },
            {
                "company": "码上云",
                "title": "Python 后端",
                "period": "2019.07 - 2022.04",
                "summary": "企业协作中台。",
                "bullets": ["FastAPI 微服务、任务队列与权限中心建设。"],
            },
        ],
        "projects": [
            {
                "name": "HR 智能对话助手",
                "period": "2024.06 - 2025.03",
                "summary": "面向招聘团队的只读智能助手。",
                "bullets": [
                    "禁止高风险写操作，仅开放搜索与解释类工具。",
                    "向量检索结果经 PostgreSQL 二次复核后返回。",
                ],
            }
        ],
        "education": {
            "school": "华南理工大学",
            "major": "计算机科学与技术",
            "degree": "硕士",
            "period": "2016.09 - 2019.06",
            "note": "方向：对话系统",
            "bullets": [],
        },
        "skills": ["Python", "FastAPI", "Milvus", "LangGraph", "RAG", "Agent", "Tool Calling"],
        "other": ["期望薪资：40K-50K", "接受混合办公"],
    },
    {
        "synthetic_key": "rag_es_01",
        "category": "RAG-ES近似",
        "tags": ["Python", "Elasticsearch", "RAG", "LangChain"],
        "status": "AI筛选通过",
        "department": "算法/AI平台",
        "name": "陆景琛",
        "headline": "RAG 应用工程师｜Elasticsearch / LangChain｜4年经验",
        "target_position": "RAG 工程师",
        "years": 4,
        "city": "杭州",
        "phone": "138-1001-0004",
        "email": "lu.jingchen@example.com",
        "availability": "2周内",
        "relevant_for": ["企业知识库问答", "RAG"],
        "distractor_for": ["Python FastAPI Milvus"],
        "eval_notes": "干扰：会做 RAG，但检索栈是 Elasticsearch，不是 Milvus。",
        "highlights": [
            "熟悉基于 Elasticsearch 的混合检索与 RAG 编排，能落地知识库问答。",
            "使用 Python、LangChain 完成分片、召回与答案生成。",
            "没有 Milvus / FastAPI 生产经验，检索服务主要挂在 Django 上。",
        ],
        "experiences": [
            {
                "company": "杭研数智",
                "title": "RAG 应用开发",
                "period": "2023.01 - 至今",
                "summary": "企业知识库基于 ES 向量检索。",
                "bullets": [
                    "在 Elasticsearch 中配置 dense_vector 字段与 kNN 召回。",
                    "Django 提供问答 API，LangChain 负责 prompt 与引用。",
                    "做过同义词扩展，但未使用 Milvus。",
                ],
            },
            {
                "company": "青叶互动",
                "title": "Python 开发",
                "period": "2021.06 - 2022.12",
                "summary": "内容平台后端。",
                "bullets": ["Django + Celery 开发内容审核链路。"],
            },
        ],
        "projects": [
            {
                "name": "客服知识库问答",
                "period": "2024.02 - 2024.11",
                "summary": "ES + LangChain RAG。",
                "bullets": ["完成 FAQ 导入、向量化与引用展示。"],
            }
        ],
        "education": {
            "school": "浙江工业大学",
            "major": "软件工程",
            "degree": "本科",
            "period": "2017.09 - 2021.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Python", "Elasticsearch", "RAG", "LangChain", "Django", "BM25", "kNN"],
        "other": ["期望薪资：28K-36K"],
    },
    {
        "synthetic_key": "rag_qdrant_01",
        "category": "RAG-Qdrant近似",
        "tags": ["Python", "Qdrant", "RAG", "FastAPI"],
        "status": "已投递",
        "department": "算法/AI平台",
        "name": "沈知微",
        "headline": "向量检索工程师｜Qdrant / FastAPI / RAG｜3年经验",
        "target_position": "向量检索工程师",
        "years": 3,
        "city": "成都",
        "phone": "138-1001-0005",
        "email": "shen.zhiwei@example.com",
        "availability": "1个月",
        "relevant_for": ["企业知识库问答", "RAG"],
        "distractor_for": ["Python FastAPI Milvus"],
        "eval_notes": "干扰：Python+FastAPI+RAG，向量库是 Qdrant。",
        "highlights": [
            "熟悉 Qdrant 集合设计、过滤条件与 RAG 检索链路。",
            "能用 FastAPI 对外提供检索服务，具备 Python 工程能力。",
            "了解 Milvus 概念，但生产实际未落地 Milvus。",
        ],
        "experiences": [
            {
                "company": "蜀云智能",
                "title": "RAG 工程师",
                "period": "2023.06 - 至今",
                "summary": "文档问答基于 Qdrant。",
                "bullets": [
                    "使用 Qdrant 存储 chunk 向量，支持 payload 过滤。",
                    "FastAPI 暴露 /search 与 /ask，对接前端工作台。",
                    "做过重新分块与 hybrid 评分尝试。",
                ],
            },
            {
                "company": "凌波科技",
                "title": "初级后端",
                "period": "2022.07 - 2023.05",
                "summary": "Python API 开发。",
                "bullets": ["Flask 小工具与数据导入脚本。"],
            },
        ],
        "projects": [
            {
                "name": "合同条款检索助手",
                "period": "2024.03 - 2024.12",
                "summary": "Qdrant RAG。",
                "bullets": ["支持条款定位与原文高亮。"],
            }
        ],
        "education": {
            "school": "电子科技大学",
            "major": "人工智能",
            "degree": "本科",
            "period": "2018.09 - 2022.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Python", "FastAPI", "Qdrant", "RAG", "Embedding", "向量检索"],
        "other": ["期望薪资：26K-34K"],
    },
    {
        "synthetic_key": "agent_no_rag_01",
        "category": "Agent无RAG",
        "tags": ["Python", "Agent", "LangGraph", "Tool Calling"],
        "status": "待面试",
        "department": "算法/AI平台",
        "name": "曹予安",
        "headline": "Agent 工程师｜多工具编排 / 工作流｜4年经验",
        "target_position": "Agent 应用工程师",
        "years": 4,
        "city": "上海",
        "phone": "138-1001-0006",
        "email": "cao.yuan@example.com",
        "availability": "2周内",
        "relevant_for": ["Agent"],
        "distractor_for": ["RAG", "Python FastAPI Milvus", "企业知识库问答"],
        "eval_notes": "干扰：有 Agent，但明确无向量库/RAG。",
        "highlights": [
            "专注 LLM Agent、工具调用与流程编排，擅长把业务 API 变成 Agent 可调用工具。",
            "熟悉 Python、LangGraph、函数调用协议，但不做向量检索与知识库。",
            "强调权限边界：写操作需人工确认，默认只读工具。",
        ],
        "experiences": [
            {
                "company": "流光 AI",
                "title": "Agent 工程师",
                "period": "2023.02 - 至今",
                "summary": "企业内部流程助手。",
                "bullets": [
                    "用 LangGraph 设计工单查询、排班查询、日历创建多工具编排。",
                    "对接现有 CRM/HRIS REST API，未引入向量数据库。",
                    "沉淀轨迹回放与失败重试策略。",
                ],
            },
            {
                "company": "麦穗软件",
                "title": "Python 开发",
                "period": "2021.07 - 2023.01",
                "summary": "自动化脚本与集成。",
                "bullets": ["编写数据同步与 webhook 处理服务。"],
            },
        ],
        "projects": [
            {
                "name": "多系统操作助手",
                "period": "2024.01 - 2024.10",
                "summary": "无 RAG，仅工具调用。",
                "bullets": ["工具白名单 + 人工确认节点，避免误操作。"],
            }
        ],
        "education": {
            "school": "上海大学",
            "major": "计算机科学与技术",
            "degree": "本科",
            "period": "2017.09 - 2021.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["Python", "Agent", "LangGraph", "Tool Calling", "工作流编排", "REST 集成"],
        "other": ["期望薪资：30K-40K"],
    },
    {
        "synthetic_key": "nlp_algo_01",
        "category": "NLP算法",
        "tags": ["NLP", "文本分类", "NER", "PyTorch", "编译优化"],
        "status": "AI筛选未通过",
        "department": "算法/AI平台",
        "name": "叶若川",
        "headline": "NLP 算法工程师｜文本分类 / NER / 训练推理｜5年经验",
        "target_position": "NLP 算法工程师",
        "years": 5,
        "city": "北京",
        "phone": "138-1001-0007",
        "email": "ye.ruochuan@example.com",
        "availability": "1个月",
        "relevant_for": ["NLP算法"],
        "distractor_for": ["RAG", "Python FastAPI Milvus"],
        "eval_notes": "含「编译优化/高性能计算」近似词，用于空结果拒答阈值检验。",
        "highlights": [
            "长期从事文本分类、NER 与搜索相关性模型，熟悉 PyTorch 训练与评估。",
            "有推理性能优化经验，做过 ONNX 导出与算子融合方向的编译优化尝试。",
            "关注标注体系与误差分析，不直接做 RAG 工程落地；涉足高性能计算向推理加速。",
        ],
        "experiences": [
            {
                "company": "中关村智算",
                "title": "NLP 算法工程师",
                "period": "2021.04 - 至今",
                "summary": "简历解析与技能实体抽取。",
                "bullets": [
                    "训练技能/公司/学历 NER，F1 提升至 0.91。",
                    "做模型量化与高性能计算向推理加速，吞吐提升 1.8x。",
                    "协助分词词典与近义词规则，服务搜索召回。",
                ],
            },
            {
                "company": "清研实验室",
                "title": "算法工程师",
                "period": "2019.07 - 2021.03",
                "summary": "文本分类与序列标注。",
                "bullets": ["多标签意图分类与主动学习采样。"],
            },
        ],
        "projects": [
            {
                "name": "中文技能实体抽取",
                "period": "2023.05 - 2024.04",
                "summary": "算法模型项目。",
                "bullets": ["无 Milvus/FastAPI 工程职责，侧重模型效果。"],
            }
        ],
        "education": {
            "school": "清华大学",
            "major": "计算机科学与技术",
            "degree": "硕士",
            "period": "2016.09 - 2019.06",
            "note": "方向：自然语言处理",
            "bullets": ["发表 NLP 会议论文 1 篇"],
        },
        "skills": ["NLP", "PyTorch", "NER", "文本分类", "ONNX", "编译优化", "高性能计算"],
        "other": ["期望薪资：38K-48K"],
    },
    {
        "synthetic_key": "ai_pm_tech_01",
        "category": "AI产品(技术侧干扰)",
        "tags": ["AI产品", "RAG", "LangChain", "需求"],
        "status": "已投递",
        "department": "产品部",
        "name": "顾清月",
        "headline": "AI 产品经理｜知识库问答 / Agent 产品｜6年经验",
        "target_position": "AI 产品经理",
        "years": 6,
        "city": "上海",
        "phone": "138-1001-0008",
        "email": "gu.qingyue@example.com",
        "availability": "2周内",
        "relevant_for": [],
        "distractor_for": ["Python FastAPI Milvus", "RAG", "企业知识库问答"],
        "eval_notes": "强干扰：文案大量出现 RAG/LangChain/Milvus，但不写代码。",
        "highlights": [
            "负责企业知识库问答与招聘助手产品规划，熟悉 RAG、LangChain、Milvus 等技术概念。",
            "能拆解召回率、引用可追溯、拒答率等指标，推动研发排期。",
            "本人不负责编码实现，聚焦需求、体验与业务验收。",
        ],
        "experiences": [
            {
                "company": "智聘云",
                "title": "AI 产品经理",
                "period": "2022.03 - 至今",
                "summary": "招聘智能助手产品负责人。",
                "bullets": [
                    "定义「Python FastAPI Milvus」类人才搜索场景与评测标准。",
                    "协调算法/工程落地 RAG，推动权限与审计需求。",
                    "输出 PRD、验收用例与上线复盘，不参与代码开发。",
                ],
            },
            {
                "company": "云图软件",
                "title": "B 端产品经理",
                "period": "2019.05 - 2022.02",
                "summary": "HR SaaS。",
                "bullets": ["候选人漏斗、面试安排等功能规划。"],
            },
        ],
        "projects": [
            {
                "name": "企业知识库问答产品化",
                "period": "2024.01 - 2024.12",
                "summary": "产品侧项目。",
                "bullets": ["梳理文档类型、引用展示与管理员后台需求。"],
            }
        ],
        "education": {
            "school": "上海交通大学",
            "major": "工业工程",
            "degree": "本科",
            "period": "2013.09 - 2017.06",
            "note": "",
            "bullets": [],
        },
        "skills": ["AI产品", "RAG产品", "需求管理", "指标设计", "用户调研", "PRD"],
        "other": ["期望薪资：35K-45K", "关注长期激励"],
    },
]
